import Link from "next/link";
import { createClass } from "../actions";
import { requireTeacher } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type PageProps = { searchParams: Promise<{ error?: string; success?: string }> };
export default async function ClassesPage({ searchParams }: PageProps) {
  const teacher = await requireTeacher(); const params = await searchParams; const supabase = await createClient(); const [{ data: classes }, { data: memberships }] = await Promise.all([supabase.from("classes").select("id, name, grade_level, academic_year").eq("teacher_id", teacher.id).order("grade_level").order("name"), supabase.from("class_members").select("class_id")]);
  const memberCounts = new Map<string, number>(); memberships?.forEach(({ class_id }) => memberCounts.set(class_id, (memberCounts.get(class_id) ?? 0) + 1));
  return <main className="teacher-main"><section className="page-heading"><div><p className="eyebrow">Class management</p><h1>Your classes</h1><p>Create and organize the groups you teach.</p></div></section>{params.error && <p className="notice notice-error" role="alert">{params.error}</p>}{params.success && <p className="notice notice-success">{params.success}</p>}<div className="teacher-two-column"><section className="teacher-section"><div className="section-row"><h2>Classes</h2><span className="muted-count">{classes?.length ?? 0} total</span></div>{classes?.length ? <div className="class-list">{classes.map((classroom) => <Link href={`/teacher/classes/${classroom.id}`} key={classroom.id}><div><strong>{classroom.name}</strong><span>Grade {classroom.grade_level} · {classroom.academic_year}</span></div><small>{memberCounts.get(classroom.id) ?? 0} students <b>→</b></small></Link>)}</div> : <div className="compact-empty"><h3>No classes yet.</h3><p>Your new classes will appear here.</p></div>}</section><aside className="teacher-form-card"><p className="eyebrow">New class</p><h2>Create a class</h2><form action={createClass}><label>Class name<input name="name" placeholder="e.g. 11A" required /></label><label>Grade<select name="grade_level" defaultValue=""><option disabled value="">Choose grade</option><option value="11">Grade 11</option><option value="12">Grade 12</option></select></label><label>Academic year<input name="academic_year" placeholder="e.g. 2026–2027" required /></label><button className="teacher-button" type="submit">Create class <span>→</span></button></form></aside></div></main>;
}
