-- DO NOT EDIT MANUALLY
-- Generated from data/skills.json by scripts/generate-skill-seed.mjs
-- 125 Jaguar Math skills

begin;

insert into public.skills (code, domain, subdomain, name, sort_order, active, notes) values
  ('NUM.ORDER_OPS', 'Number & Quantitative Reasoning', 'Arithmetic', 'Use order of operations accurately', '1', 'true', 'Foundational prerequisite; ICFES includes basic arithmetic operations.'),
  ('NUM.INTEGER_OPS', 'Number & Quantitative Reasoning', 'Arithmetic', 'Perform operations with integers and signed numbers', '2', 'true', NULL),
  ('NUM.FRACTIONS', 'Number & Quantitative Reasoning', 'Arithmetic', 'Perform operations with fractions and mixed numbers', '3', 'true', NULL),
  ('NUM.DECIMALS', 'Number & Quantitative Reasoning', 'Arithmetic', 'Perform operations with decimals', '4', 'true', NULL),
  ('NUM.RATIOS_RATES', 'Number & Quantitative Reasoning', 'Proportional Reasoning', 'Work with ratios, rates, and unit rates', '5', 'true', NULL),
  ('NUM.PROPORTIONS', 'Number & Quantitative Reasoning', 'Proportional Reasoning', 'Solve proportional relationships', '6', 'true', NULL),
  ('NUM.PERCENT', 'Number & Quantitative Reasoning', 'Proportional Reasoning', 'Solve percent problems and percent change', '7', 'true', NULL),
  ('NUM.UNITS', 'Number & Quantitative Reasoning', 'Measurement', 'Convert units and use dimensional analysis', '8', 'true', NULL),
  ('NUM.SCI_NOTATION', 'Number & Quantitative Reasoning', 'Number Systems', 'Use scientific notation and orders of magnitude', '9', 'true', NULL),
  ('NUM.ESTIMATION', 'Number & Quantitative Reasoning', 'Quantitative Reasoning', 'Estimate, approximate, and judge reasonableness', '10', 'true', NULL),
  ('NUM.REAL_NUMBERS', 'Number & Quantitative Reasoning', 'Number Systems', 'Classify and compare rational, irrational, and real numbers', '11', 'true', NULL),
  ('ALG.EXPRESSIONS', 'Algebra', 'Expressions', 'Simplify and evaluate algebraic expressions', '12', 'true', NULL),
  ('ALG.EQUIVALENT_EXPRESSIONS', 'Algebra', 'Expressions', 'Rewrite expressions in equivalent forms to reveal structure', '13', 'true', NULL),
  ('ALG.REARRANGE_FORMULAS', 'Algebra', 'Expressions', 'Rearrange formulas and literal equations', '14', 'true', NULL),
  ('ALG.ABSOLUTE_VALUE', 'Algebra', 'Equations & Inequalities', 'Solve and interpret absolute-value equations and inequalities', '15', 'true', NULL),
  ('ALG.LINEAR_EQ_1VAR', 'Algebra', 'Linear Equations', 'Solve linear equations in one variable', '16', 'true', NULL),
  ('ALG.LINEAR_EQ_2VAR', 'Algebra', 'Linear Equations', 'Interpret and work with linear equations in two variables', '17', 'true', NULL),
  ('ALG.LINEAR_EQ_CONTEXT', 'Algebra', 'Linear Equations', 'Model and solve contextual problems with linear equations', '18', 'true', NULL),
  ('ALG.LINEAR_INEQUALITIES', 'Algebra', 'Inequalities', 'Solve and graph linear inequalities in one or two variables', '19', 'true', NULL),
  ('ALG.COMPOUND_INEQUALITIES', 'Algebra', 'Inequalities', 'Solve compound inequalities and interval constraints', '20', 'true', NULL),
  ('ALG.SYSTEMS_LINEAR', 'Algebra', 'Systems', 'Solve systems of two linear equations', '21', 'true', NULL),
  ('ALG.SYSTEMS_CONTEXT', 'Algebra', 'Systems', 'Model and interpret contextual situations with systems', '22', 'true', NULL),
  ('ALG.NONLINEAR_SYSTEMS', 'Algebra', 'Systems', 'Solve systems containing nonlinear equations', '23', 'true', NULL),
  ('ALG.EXPONENT_RULES', 'Algebra', 'Exponents & Radicals', 'Apply laws of exponents', '24', 'true', NULL),
  ('ALG.RADICALS', 'Algebra', 'Exponents & Radicals', 'Simplify and operate with radical expressions', '25', 'true', NULL),
  ('ALG.RATIONAL_EXPONENTS', 'Algebra', 'Exponents & Radicals', 'Work with rational exponents and connect them to radicals', '26', 'true', NULL),
  ('ALG.RADICAL_EQUATIONS', 'Algebra', 'Exponents & Radicals', 'Solve radical equations and check extraneous solutions', '27', 'true', NULL),
  ('ALG.POLYNOMIAL_OPS', 'Algebra', 'Polynomials', 'Add, subtract, and multiply polynomials', '28', 'true', NULL),
  ('ALG.FACTORING', 'Algebra', 'Polynomials', 'Factor polynomial expressions', '29', 'true', NULL),
  ('ALG.POLYNOMIAL_DIVISION', 'Algebra', 'Polynomials', 'Divide polynomials and rational polynomial expressions', '30', 'true', NULL),
  ('ALG.POLYNOMIAL_ZEROS', 'Algebra', 'Polynomials', 'Use zeros, factors, and the remainder/factor theorems', '31', 'true', NULL),
  ('ALG.BINOMIAL_THEOREM', 'Algebra', 'Polynomials', 'Use the binomial theorem and polynomial identities', '32', 'true', NULL),
  ('ALG.QUADRATIC_SOLVE', 'Algebra', 'Quadratics', 'Solve quadratic equations using appropriate methods', '33', 'true', NULL),
  ('ALG.QUADRATIC_DISCRIMINANT', 'Algebra', 'Quadratics', 'Use the discriminant to determine the number and type of solutions', '34', 'true', NULL),
  ('ALG.RATIONAL_EXPRESSIONS', 'Algebra', 'Rational Algebra', 'Simplify and operate with rational expressions', '35', 'true', NULL),
  ('ALG.RATIONAL_EQUATIONS', 'Algebra', 'Rational Algebra', 'Solve rational equations and identify excluded values', '36', 'true', NULL),
  ('FUNC.CONCEPT', 'Functions', 'Foundations', 'Understand functions, inputs, outputs, and function notation', '37', 'true', NULL),
  ('FUNC.DOMAIN_RANGE', 'Functions', 'Foundations', 'Determine and interpret domain and range', '38', 'true', NULL),
  ('FUNC.MULTIPLE_REPRESENTATIONS', 'Functions', 'Foundations', 'Connect equations, tables, graphs, and verbal descriptions', '39', 'true', NULL),
  ('FUNC.GRAPH_FEATURES', 'Functions', 'Foundations', 'Interpret intercepts, extrema, intervals, symmetry, and end behavior from graphs', '40', 'true', NULL),
  ('FUNC.RATE_CHANGE', 'Functions', 'Foundations', 'Calculate and interpret average rate of change', '41', 'true', NULL),
  ('FUNC.COMPARE', 'Functions', 'Foundations', 'Compare functions represented in different forms', '42', 'true', NULL),
  ('FUNC.TRANSFORMATIONS', 'Functions', 'Transformations', 'Analyze translations, reflections, stretches, and compressions', '43', 'true', NULL),
  ('FUNC.COMPOSITION', 'Functions', 'Operations on Functions', 'Compose functions and interpret compositions', '44', 'true', NULL),
  ('FUNC.INVERSE', 'Functions', 'Operations on Functions', 'Find, verify, and interpret inverse functions', '45', 'true', NULL),
  ('FUNC.PIECEWISE', 'Functions', 'Special Functions', 'Interpret, graph, and evaluate piecewise-defined functions', '46', 'true', NULL),
  ('FUNC.LINEAR', 'Functions', 'Linear Functions', 'Analyze and represent linear functions', '47', 'true', NULL),
  ('FUNC.LINEAR_MODELING', 'Functions', 'Linear Functions', 'Build and interpret linear models from context or data', '48', 'true', NULL),
  ('FUNC.QUADRATIC', 'Functions', 'Quadratic Functions', 'Analyze quadratic functions and their key features', '49', 'true', NULL),
  ('FUNC.QUADRATIC_FORMS', 'Functions', 'Quadratic Functions', 'Connect standard, vertex, and factored forms of quadratics', '50', 'true', NULL),
  ('FUNC.QUADRATIC_MODELING', 'Functions', 'Quadratic Functions', 'Model contextual situations using quadratic functions', '51', 'true', NULL),
  ('FUNC.POLYNOMIAL', 'Functions', 'Polynomial & Rational Functions', 'Analyze polynomial functions, zeros, and end behavior', '52', 'true', NULL),
  ('FUNC.RATIONAL', 'Functions', 'Polynomial & Rational Functions', 'Analyze rational functions, asymptotes, holes, and domain restrictions', '53', 'true', NULL),
  ('FUNC.EXPONENTIAL', 'Functions', 'Exponential & Logarithmic Functions', 'Analyze exponential functions and compare exponential versus linear growth', '54', 'true', NULL),
  ('FUNC.EXPONENTIAL_MODELING', 'Functions', 'Exponential & Logarithmic Functions', 'Model growth and decay with exponential functions', '55', 'true', NULL),
  ('FUNC.LOGARITHMIC', 'Functions', 'Exponential & Logarithmic Functions', 'Analyze logarithmic functions and solve exponential/logarithmic equations', '56', 'true', NULL),
  ('GEO.ANGLES_LINES', 'Geometry', 'Lines & Angles', 'Use angle relationships and properties of parallel/perpendicular lines', '57', 'true', NULL),
  ('GEO.TRIANGLES', 'Geometry', 'Triangles', 'Apply triangle properties, angle sums, and triangle inequality', '58', 'true', NULL),
  ('GEO.CONGRUENCE', 'Geometry', 'Triangles', 'Use triangle congruence criteria and rigid-motion reasoning', '59', 'true', NULL),
  ('GEO.SIMILARITY', 'Geometry', 'Triangles', 'Use similarity, scale factors, and proportional relationships in figures', '60', 'true', NULL),
  ('GEO.PYTHAGOREAN', 'Geometry', 'Triangles', 'Apply the Pythagorean theorem and related distance relationships', '61', 'true', NULL),
  ('GEO.POLYGONS', 'Geometry', 'Polygons', 'Analyze polygons, angle sums, and properties of quadrilaterals', '62', 'true', NULL),
  ('GEO.CIRCLES', 'Geometry', 'Circles', 'Apply circle properties involving chords, tangents, arcs, and angles', '63', 'true', NULL),
  ('GEO.CIRCLE_EQUATIONS', 'Geometry', 'Circles', 'Use the equation of a circle in the coordinate plane', '64', 'true', NULL),
  ('GEO.CIRCLE_MEASURE', 'Geometry', 'Circles', 'Work with circumference, arc length, sector area, and radian-based circle measure', '65', 'true', NULL),
  ('GEO.AREA', 'Geometry', 'Measurement', 'Calculate and reason with area of two-dimensional figures', '66', 'true', NULL),
  ('GEO.SURFACE_AREA', 'Geometry', 'Measurement', 'Calculate surface area of three-dimensional solids', '67', 'true', NULL),
  ('GEO.VOLUME', 'Geometry', 'Measurement', 'Calculate and reason with volume of three-dimensional solids', '68', 'true', NULL),
  ('GEO.COORDINATE', 'Geometry', 'Coordinate Geometry', 'Use slope, distance, midpoint, partition, and coordinates to solve geometry problems', '69', 'true', NULL),
  ('GEO.TRANSFORMATIONS', 'Geometry', 'Transformations', 'Use translations, rotations, reflections, and dilations', '70', 'true', NULL),
  ('GEO.GEOMETRIC_REASONING', 'Geometry', 'Reasoning & Proof', 'Construct and justify geometric arguments and proofs', '71', 'true', NULL),
  ('GEO.MODELING', 'Geometry', 'Modeling', 'Model real objects and constraints using geometric shapes, measures, and density', '72', 'true', NULL),
  ('TRIG.RIGHT_TRIANGLE', 'Trigonometry', 'Right-Triangle Trigonometry', 'Solve right triangles using sine, cosine, and tangent', '73', 'true', NULL),
  ('TRIG.SPECIAL_TRIANGLES', 'Trigonometry', 'Right-Triangle Trigonometry', 'Use 30-60-90 and 45-45-90 triangles and exact values', '74', 'true', NULL),
  ('TRIG.RADIANS', 'Trigonometry', 'Unit Circle', 'Convert between degrees and radians and use radian measure', '75', 'true', NULL),
  ('TRIG.UNIT_CIRCLE', 'Trigonometry', 'Unit Circle', 'Use the unit circle to determine exact trigonometric values', '76', 'true', NULL),
  ('TRIG.GRAPHS', 'Trigonometry', 'Trig Functions', 'Analyze graphs of sine, cosine, and tangent', '77', 'true', NULL),
  ('TRIG.TRANSFORMATIONS', 'Trigonometry', 'Trig Functions', 'Analyze amplitude, period, phase shift, and vertical shift', '78', 'true', NULL),
  ('TRIG.INVERSE', 'Trigonometry', 'Trig Functions', 'Use inverse trigonometric functions to determine angles and solve problems', '79', 'true', NULL),
  ('TRIG.IDENTITIES', 'Trigonometry', 'Identities & Equations', 'Simplify and verify trigonometric identities', '80', 'true', NULL),
  ('TRIG.EQUATIONS', 'Trigonometry', 'Identities & Equations', 'Solve trigonometric equations', '81', 'true', NULL),
  ('TRIG.LAW_SINES_COSINES', 'Trigonometry', 'Oblique Triangles', 'Solve non-right triangles using the Laws of Sines and Cosines', '82', 'true', NULL),
  ('TRIG.MODELING', 'Trigonometry', 'Modeling', 'Model periodic phenomena with trigonometric functions', '83', 'true', NULL),
  ('STAT.DATA_DISPLAYS', 'Statistics & Probability', 'Descriptive Statistics', 'Read, construct, and interpret tables, charts, plots, and graphs', '84', 'true', NULL),
  ('STAT.CENTER', 'Statistics & Probability', 'Descriptive Statistics', 'Calculate and interpret mean, median, and other measures of center', '85', 'true', NULL),
  ('STAT.VARIABILITY', 'Statistics & Probability', 'Descriptive Statistics', 'Calculate and interpret range, IQR, variance, and standard deviation', '86', 'true', NULL),
  ('STAT.PERCENTILES', 'Statistics & Probability', 'Descriptive Statistics', 'Interpret percentiles, quartiles, and relative position in a distribution', '87', 'true', NULL),
  ('STAT.DISTRIBUTIONS', 'Statistics & Probability', 'Descriptive Statistics', 'Describe and compare distributions using shape, center, spread, and outliers', '88', 'true', NULL),
  ('STAT.NORMAL_DISTRIBUTION', 'Statistics & Probability', 'Descriptive Statistics', 'Use normal distributions, z-scores, and standard deviation to estimate proportions', '89', 'true', NULL),
  ('STAT.SCATTERPLOTS', 'Statistics & Probability', 'Bivariate Data', 'Analyze scatterplots, association, trends, and outliers', '90', 'true', NULL),
  ('STAT.REGRESSION', 'Statistics & Probability', 'Bivariate Data', 'Interpret linear/nonlinear models, residuals, slope, intercept, and correlation', '91', 'true', NULL),
  ('STAT.TWO_WAY_TABLES', 'Statistics & Probability', 'Categorical Data', 'Analyze two-way tables, joint frequencies, and conditional frequencies', '92', 'true', NULL),
  ('STAT.SET_OPERATIONS', 'Statistics & Probability', 'Sets', 'Use intersection, union, complement, and containment of sets', '93', 'true', NULL),
  ('PROB.BASIC', 'Statistics & Probability', 'Probability', 'Calculate and interpret basic probabilities', '94', 'true', NULL),
  ('PROB.COMPOUND', 'Statistics & Probability', 'Probability', 'Calculate probabilities of compound events using addition and multiplication rules', '95', 'true', NULL),
  ('PROB.CONDITIONAL', 'Statistics & Probability', 'Probability', 'Calculate and interpret conditional probability', '96', 'true', NULL),
  ('PROB.INDEPENDENCE', 'Statistics & Probability', 'Probability', 'Determine whether events are independent and use independence appropriately', '97', 'true', NULL),
  ('PROB.COUNTING_PRINCIPLES', 'Statistics & Probability', 'Counting', 'Use fundamental counting principles and organized counting methods', '98', 'true', NULL),
  ('PROB.PERM_COMB', 'Statistics & Probability', 'Counting', 'Use permutations and combinations in counting and probability', '99', 'true', NULL),
  ('PROB.EXPECTED_VALUE', 'Statistics & Probability', 'Probability Models', 'Calculate and interpret expected value of a random variable', '100', 'true', NULL),
  ('STAT.SAMPLING', 'Statistics & Probability', 'Inference', 'Understand populations, samples, sampling methods, and sampling bias', '101', 'true', NULL),
  ('STAT.MARGIN_ERROR', 'Statistics & Probability', 'Inference', 'Interpret sampling variability, estimation error, and margin of error', '102', 'true', NULL),
  ('STAT.INFERENCE', 'Statistics & Probability', 'Inference', 'Use sample statistics to make and evaluate inferences about populations', '103', 'true', NULL),
  ('STAT.STUDY_DESIGN', 'Statistics & Probability', 'Inference', 'Distinguish surveys, observational studies, and experiments; evaluate statistical claims', '104', 'true', NULL),
  ('PRE.SEQUENCES', 'Precalculus', 'Sequences & Series', 'Analyze arithmetic and geometric sequences explicitly and recursively', '105', 'true', NULL),
  ('PRE.SERIES', 'Precalculus', 'Sequences & Series', 'Work with finite and infinite geometric series', '106', 'true', NULL),
  ('PRE.RECURSIVE', 'Precalculus', 'Sequences & Series', 'Use recursive definitions and convert between recursive and explicit forms', '107', 'true', NULL),
  ('PRE.COMPLEX_ARITHMETIC', 'Precalculus', 'Complex Numbers', 'Perform arithmetic with complex numbers and use conjugates', '108', 'true', NULL),
  ('PRE.COMPLEX_PLANE_ROOTS', 'Precalculus', 'Complex Numbers', 'Represent complex numbers geometrically and solve polynomial equations with complex roots', '109', 'true', NULL),
  ('PRE.POLAR', 'Precalculus', 'Coordinate Systems', 'Work with polar coordinates and polar representations', '110', 'true', 'Explicitly named in ICFES non-generic geometry content; no direct core AERO high-school code.'),
  ('PRE.VECTORS', 'Precalculus', 'Vectors & Matrices', 'Represent and operate with vectors and apply them to problems', '111', 'true', NULL),
  ('PRE.MATRICES', 'Precalculus', 'Vectors & Matrices', 'Perform matrix operations and use matrices to represent transformations/systems', '112', 'true', NULL),
  ('PRE.PARAMETRIC', 'Precalculus', 'Advanced Functions', 'Analyze parametric equations and their graphs', '113', 'true', NULL),
  ('PRE.CONICS', 'Precalculus', 'Conic Sections', 'Analyze parabolas, ellipses, and hyperbolas algebraically and geometrically', '114', 'true', NULL),
  ('PRE.LIMIT_INTUITION', 'Precalculus', 'Limits', 'Understand limits conceptually using tables, graphs, sequences, and behavior near a point', '115', 'true', 'ICFES explicitly includes sequences and their limits; calculus-style formal limits go beyond SAT.'),
  ('CALC.LIMITS', 'Calculus', 'Limits & Continuity', 'Evaluate and interpret limits algebraically and graphically', '116', 'true', 'Beyond AERO core/SAT; related to ICFES ''sucesiones y sus límites'' but broader.'),
  ('CALC.CONTINUITY', 'Calculus', 'Limits & Continuity', 'Determine and interpret continuity', '117', 'true', NULL),
  ('CALC.DERIVATIVE_CONCEPT', 'Calculus', 'Derivatives', 'Understand derivative as instantaneous rate of change and tangent slope', '118', 'true', NULL),
  ('CALC.DERIVATIVE_RULES', 'Calculus', 'Derivatives', 'Apply basic derivative rules, including product, quotient, and chain rules', '119', 'true', NULL),
  ('CALC.DERIVATIVE_FUNCTIONS', 'Calculus', 'Derivatives', 'Differentiate polynomial, exponential, logarithmic, and trigonometric functions', '120', 'true', NULL),
  ('CALC.DERIVATIVE_APPLICATIONS', 'Calculus', 'Applications of Derivatives', 'Apply derivatives to motion, related rates, extrema, and optimization', '121', 'true', NULL),
  ('CALC.GRAPH_ANALYSIS', 'Calculus', 'Applications of Derivatives', 'Use derivatives to analyze increasing/decreasing behavior, concavity, and extrema', '122', 'true', NULL),
  ('CALC.INTEGRAL_CONCEPT', 'Calculus', 'Integrals', 'Understand accumulation, signed area, and antiderivatives', '123', 'true', NULL),
  ('CALC.INTEGRATION', 'Calculus', 'Integrals', 'Evaluate basic indefinite and definite integrals', '124', 'true', NULL),
  ('CALC.FTC', 'Calculus', 'Integrals', 'Apply the Fundamental Theorem of Calculus', '125', 'true', NULL)
on conflict (code) do update set
  domain = excluded.domain, subdomain = excluded.subdomain, name = excluded.name,
  sort_order = excluded.sort_order, active = excluded.active, notes = excluded.notes, updated_at = now();

delete from public.skill_aero_mappings mapping using public.skills skill where mapping.skill_id = skill.id and skill.code in ('NUM.ORDER_OPS', 'NUM.INTEGER_OPS', 'NUM.FRACTIONS', 'NUM.DECIMALS', 'NUM.RATIOS_RATES', 'NUM.PROPORTIONS', 'NUM.PERCENT', 'NUM.UNITS', 'NUM.SCI_NOTATION', 'NUM.ESTIMATION', 'NUM.REAL_NUMBERS', 'ALG.EXPRESSIONS', 'ALG.EQUIVALENT_EXPRESSIONS', 'ALG.REARRANGE_FORMULAS', 'ALG.ABSOLUTE_VALUE', 'ALG.LINEAR_EQ_1VAR', 'ALG.LINEAR_EQ_2VAR', 'ALG.LINEAR_EQ_CONTEXT', 'ALG.LINEAR_INEQUALITIES', 'ALG.COMPOUND_INEQUALITIES', 'ALG.SYSTEMS_LINEAR', 'ALG.SYSTEMS_CONTEXT', 'ALG.NONLINEAR_SYSTEMS', 'ALG.EXPONENT_RULES', 'ALG.RADICALS', 'ALG.RATIONAL_EXPONENTS', 'ALG.RADICAL_EQUATIONS', 'ALG.POLYNOMIAL_OPS', 'ALG.FACTORING', 'ALG.POLYNOMIAL_DIVISION', 'ALG.POLYNOMIAL_ZEROS', 'ALG.BINOMIAL_THEOREM', 'ALG.QUADRATIC_SOLVE', 'ALG.QUADRATIC_DISCRIMINANT', 'ALG.RATIONAL_EXPRESSIONS', 'ALG.RATIONAL_EQUATIONS', 'FUNC.CONCEPT', 'FUNC.DOMAIN_RANGE', 'FUNC.MULTIPLE_REPRESENTATIONS', 'FUNC.GRAPH_FEATURES', 'FUNC.RATE_CHANGE', 'FUNC.COMPARE', 'FUNC.TRANSFORMATIONS', 'FUNC.COMPOSITION', 'FUNC.INVERSE', 'FUNC.PIECEWISE', 'FUNC.LINEAR', 'FUNC.LINEAR_MODELING', 'FUNC.QUADRATIC', 'FUNC.QUADRATIC_FORMS', 'FUNC.QUADRATIC_MODELING', 'FUNC.POLYNOMIAL', 'FUNC.RATIONAL', 'FUNC.EXPONENTIAL', 'FUNC.EXPONENTIAL_MODELING', 'FUNC.LOGARITHMIC', 'GEO.ANGLES_LINES', 'GEO.TRIANGLES', 'GEO.CONGRUENCE', 'GEO.SIMILARITY', 'GEO.PYTHAGOREAN', 'GEO.POLYGONS', 'GEO.CIRCLES', 'GEO.CIRCLE_EQUATIONS', 'GEO.CIRCLE_MEASURE', 'GEO.AREA', 'GEO.SURFACE_AREA', 'GEO.VOLUME', 'GEO.COORDINATE', 'GEO.TRANSFORMATIONS', 'GEO.GEOMETRIC_REASONING', 'GEO.MODELING', 'TRIG.RIGHT_TRIANGLE', 'TRIG.SPECIAL_TRIANGLES', 'TRIG.RADIANS', 'TRIG.UNIT_CIRCLE', 'TRIG.GRAPHS', 'TRIG.TRANSFORMATIONS', 'TRIG.INVERSE', 'TRIG.IDENTITIES', 'TRIG.EQUATIONS', 'TRIG.LAW_SINES_COSINES', 'TRIG.MODELING', 'STAT.DATA_DISPLAYS', 'STAT.CENTER', 'STAT.VARIABILITY', 'STAT.PERCENTILES', 'STAT.DISTRIBUTIONS', 'STAT.NORMAL_DISTRIBUTION', 'STAT.SCATTERPLOTS', 'STAT.REGRESSION', 'STAT.TWO_WAY_TABLES', 'STAT.SET_OPERATIONS', 'PROB.BASIC', 'PROB.COMPOUND', 'PROB.CONDITIONAL', 'PROB.INDEPENDENCE', 'PROB.COUNTING_PRINCIPLES', 'PROB.PERM_COMB', 'PROB.EXPECTED_VALUE', 'STAT.SAMPLING', 'STAT.MARGIN_ERROR', 'STAT.INFERENCE', 'STAT.STUDY_DESIGN', 'PRE.SEQUENCES', 'PRE.SERIES', 'PRE.RECURSIVE', 'PRE.COMPLEX_ARITHMETIC', 'PRE.COMPLEX_PLANE_ROOTS', 'PRE.POLAR', 'PRE.VECTORS', 'PRE.MATRICES', 'PRE.PARAMETRIC', 'PRE.CONICS', 'PRE.LIMIT_INTUITION', 'CALC.LIMITS', 'CALC.CONTINUITY', 'CALC.DERIVATIVE_CONCEPT', 'CALC.DERIVATIVE_RULES', 'CALC.DERIVATIVE_FUNCTIONS', 'CALC.DERIVATIVE_APPLICATIONS', 'CALC.GRAPH_ANALYSIS', 'CALC.INTEGRAL_CONCEPT', 'CALC.INTEGRATION', 'CALC.FTC');
delete from public.skill_sat_mappings mapping using public.skills skill where mapping.skill_id = skill.id and skill.code in ('NUM.ORDER_OPS', 'NUM.INTEGER_OPS', 'NUM.FRACTIONS', 'NUM.DECIMALS', 'NUM.RATIOS_RATES', 'NUM.PROPORTIONS', 'NUM.PERCENT', 'NUM.UNITS', 'NUM.SCI_NOTATION', 'NUM.ESTIMATION', 'NUM.REAL_NUMBERS', 'ALG.EXPRESSIONS', 'ALG.EQUIVALENT_EXPRESSIONS', 'ALG.REARRANGE_FORMULAS', 'ALG.ABSOLUTE_VALUE', 'ALG.LINEAR_EQ_1VAR', 'ALG.LINEAR_EQ_2VAR', 'ALG.LINEAR_EQ_CONTEXT', 'ALG.LINEAR_INEQUALITIES', 'ALG.COMPOUND_INEQUALITIES', 'ALG.SYSTEMS_LINEAR', 'ALG.SYSTEMS_CONTEXT', 'ALG.NONLINEAR_SYSTEMS', 'ALG.EXPONENT_RULES', 'ALG.RADICALS', 'ALG.RATIONAL_EXPONENTS', 'ALG.RADICAL_EQUATIONS', 'ALG.POLYNOMIAL_OPS', 'ALG.FACTORING', 'ALG.POLYNOMIAL_DIVISION', 'ALG.POLYNOMIAL_ZEROS', 'ALG.BINOMIAL_THEOREM', 'ALG.QUADRATIC_SOLVE', 'ALG.QUADRATIC_DISCRIMINANT', 'ALG.RATIONAL_EXPRESSIONS', 'ALG.RATIONAL_EQUATIONS', 'FUNC.CONCEPT', 'FUNC.DOMAIN_RANGE', 'FUNC.MULTIPLE_REPRESENTATIONS', 'FUNC.GRAPH_FEATURES', 'FUNC.RATE_CHANGE', 'FUNC.COMPARE', 'FUNC.TRANSFORMATIONS', 'FUNC.COMPOSITION', 'FUNC.INVERSE', 'FUNC.PIECEWISE', 'FUNC.LINEAR', 'FUNC.LINEAR_MODELING', 'FUNC.QUADRATIC', 'FUNC.QUADRATIC_FORMS', 'FUNC.QUADRATIC_MODELING', 'FUNC.POLYNOMIAL', 'FUNC.RATIONAL', 'FUNC.EXPONENTIAL', 'FUNC.EXPONENTIAL_MODELING', 'FUNC.LOGARITHMIC', 'GEO.ANGLES_LINES', 'GEO.TRIANGLES', 'GEO.CONGRUENCE', 'GEO.SIMILARITY', 'GEO.PYTHAGOREAN', 'GEO.POLYGONS', 'GEO.CIRCLES', 'GEO.CIRCLE_EQUATIONS', 'GEO.CIRCLE_MEASURE', 'GEO.AREA', 'GEO.SURFACE_AREA', 'GEO.VOLUME', 'GEO.COORDINATE', 'GEO.TRANSFORMATIONS', 'GEO.GEOMETRIC_REASONING', 'GEO.MODELING', 'TRIG.RIGHT_TRIANGLE', 'TRIG.SPECIAL_TRIANGLES', 'TRIG.RADIANS', 'TRIG.UNIT_CIRCLE', 'TRIG.GRAPHS', 'TRIG.TRANSFORMATIONS', 'TRIG.INVERSE', 'TRIG.IDENTITIES', 'TRIG.EQUATIONS', 'TRIG.LAW_SINES_COSINES', 'TRIG.MODELING', 'STAT.DATA_DISPLAYS', 'STAT.CENTER', 'STAT.VARIABILITY', 'STAT.PERCENTILES', 'STAT.DISTRIBUTIONS', 'STAT.NORMAL_DISTRIBUTION', 'STAT.SCATTERPLOTS', 'STAT.REGRESSION', 'STAT.TWO_WAY_TABLES', 'STAT.SET_OPERATIONS', 'PROB.BASIC', 'PROB.COMPOUND', 'PROB.CONDITIONAL', 'PROB.INDEPENDENCE', 'PROB.COUNTING_PRINCIPLES', 'PROB.PERM_COMB', 'PROB.EXPECTED_VALUE', 'STAT.SAMPLING', 'STAT.MARGIN_ERROR', 'STAT.INFERENCE', 'STAT.STUDY_DESIGN', 'PRE.SEQUENCES', 'PRE.SERIES', 'PRE.RECURSIVE', 'PRE.COMPLEX_ARITHMETIC', 'PRE.COMPLEX_PLANE_ROOTS', 'PRE.POLAR', 'PRE.VECTORS', 'PRE.MATRICES', 'PRE.PARAMETRIC', 'PRE.CONICS', 'PRE.LIMIT_INTUITION', 'CALC.LIMITS', 'CALC.CONTINUITY', 'CALC.DERIVATIVE_CONCEPT', 'CALC.DERIVATIVE_RULES', 'CALC.DERIVATIVE_FUNCTIONS', 'CALC.DERIVATIVE_APPLICATIONS', 'CALC.GRAPH_ANALYSIS', 'CALC.INTEGRAL_CONCEPT', 'CALC.INTEGRATION', 'CALC.FTC');
delete from public.skill_icfes_mappings mapping using public.skills skill where mapping.skill_id = skill.id and skill.code in ('NUM.ORDER_OPS', 'NUM.INTEGER_OPS', 'NUM.FRACTIONS', 'NUM.DECIMALS', 'NUM.RATIOS_RATES', 'NUM.PROPORTIONS', 'NUM.PERCENT', 'NUM.UNITS', 'NUM.SCI_NOTATION', 'NUM.ESTIMATION', 'NUM.REAL_NUMBERS', 'ALG.EXPRESSIONS', 'ALG.EQUIVALENT_EXPRESSIONS', 'ALG.REARRANGE_FORMULAS', 'ALG.ABSOLUTE_VALUE', 'ALG.LINEAR_EQ_1VAR', 'ALG.LINEAR_EQ_2VAR', 'ALG.LINEAR_EQ_CONTEXT', 'ALG.LINEAR_INEQUALITIES', 'ALG.COMPOUND_INEQUALITIES', 'ALG.SYSTEMS_LINEAR', 'ALG.SYSTEMS_CONTEXT', 'ALG.NONLINEAR_SYSTEMS', 'ALG.EXPONENT_RULES', 'ALG.RADICALS', 'ALG.RATIONAL_EXPONENTS', 'ALG.RADICAL_EQUATIONS', 'ALG.POLYNOMIAL_OPS', 'ALG.FACTORING', 'ALG.POLYNOMIAL_DIVISION', 'ALG.POLYNOMIAL_ZEROS', 'ALG.BINOMIAL_THEOREM', 'ALG.QUADRATIC_SOLVE', 'ALG.QUADRATIC_DISCRIMINANT', 'ALG.RATIONAL_EXPRESSIONS', 'ALG.RATIONAL_EQUATIONS', 'FUNC.CONCEPT', 'FUNC.DOMAIN_RANGE', 'FUNC.MULTIPLE_REPRESENTATIONS', 'FUNC.GRAPH_FEATURES', 'FUNC.RATE_CHANGE', 'FUNC.COMPARE', 'FUNC.TRANSFORMATIONS', 'FUNC.COMPOSITION', 'FUNC.INVERSE', 'FUNC.PIECEWISE', 'FUNC.LINEAR', 'FUNC.LINEAR_MODELING', 'FUNC.QUADRATIC', 'FUNC.QUADRATIC_FORMS', 'FUNC.QUADRATIC_MODELING', 'FUNC.POLYNOMIAL', 'FUNC.RATIONAL', 'FUNC.EXPONENTIAL', 'FUNC.EXPONENTIAL_MODELING', 'FUNC.LOGARITHMIC', 'GEO.ANGLES_LINES', 'GEO.TRIANGLES', 'GEO.CONGRUENCE', 'GEO.SIMILARITY', 'GEO.PYTHAGOREAN', 'GEO.POLYGONS', 'GEO.CIRCLES', 'GEO.CIRCLE_EQUATIONS', 'GEO.CIRCLE_MEASURE', 'GEO.AREA', 'GEO.SURFACE_AREA', 'GEO.VOLUME', 'GEO.COORDINATE', 'GEO.TRANSFORMATIONS', 'GEO.GEOMETRIC_REASONING', 'GEO.MODELING', 'TRIG.RIGHT_TRIANGLE', 'TRIG.SPECIAL_TRIANGLES', 'TRIG.RADIANS', 'TRIG.UNIT_CIRCLE', 'TRIG.GRAPHS', 'TRIG.TRANSFORMATIONS', 'TRIG.INVERSE', 'TRIG.IDENTITIES', 'TRIG.EQUATIONS', 'TRIG.LAW_SINES_COSINES', 'TRIG.MODELING', 'STAT.DATA_DISPLAYS', 'STAT.CENTER', 'STAT.VARIABILITY', 'STAT.PERCENTILES', 'STAT.DISTRIBUTIONS', 'STAT.NORMAL_DISTRIBUTION', 'STAT.SCATTERPLOTS', 'STAT.REGRESSION', 'STAT.TWO_WAY_TABLES', 'STAT.SET_OPERATIONS', 'PROB.BASIC', 'PROB.COMPOUND', 'PROB.CONDITIONAL', 'PROB.INDEPENDENCE', 'PROB.COUNTING_PRINCIPLES', 'PROB.PERM_COMB', 'PROB.EXPECTED_VALUE', 'STAT.SAMPLING', 'STAT.MARGIN_ERROR', 'STAT.INFERENCE', 'STAT.STUDY_DESIGN', 'PRE.SEQUENCES', 'PRE.SERIES', 'PRE.RECURSIVE', 'PRE.COMPLEX_ARITHMETIC', 'PRE.COMPLEX_PLANE_ROOTS', 'PRE.POLAR', 'PRE.VECTORS', 'PRE.MATRICES', 'PRE.PARAMETRIC', 'PRE.CONICS', 'PRE.LIMIT_INTUITION', 'CALC.LIMITS', 'CALC.CONTINUITY', 'CALC.DERIVATIVE_CONCEPT', 'CALC.DERIVATIVE_RULES', 'CALC.DERIVATIVE_FUNCTIONS', 'CALC.DERIVATIVE_APPLICATIONS', 'CALC.GRAPH_ANALYSIS', 'CALC.INTEGRAL_CONCEPT', 'CALC.INTEGRATION', 'CALC.FTC');

insert into public.skill_aero_mappings (skill_id, aero_code, mapping_status)
select skill.id, seed.aero_code, seed.mapping_status
from (values
  ('NUM.ORDER_OPS', NULL, 'prerequisite'),
  ('NUM.INTEGER_OPS', NULL, 'prerequisite'),
  ('NUM.FRACTIONS', NULL, 'prerequisite'),
  ('NUM.DECIMALS', NULL, 'prerequisite'),
  ('NUM.RATIOS_RATES', 'AERO.HSN.Q.1', 'direct'),
  ('NUM.PROPORTIONS', 'AERO.HSN.Q.1', 'direct'),
  ('NUM.PROPORTIONS', 'AERO.HSF.LE.1', 'direct'),
  ('NUM.PERCENT', 'AERO.HSN.Q.1', 'partial'),
  ('NUM.UNITS', 'AERO.HSN.Q.1-3', 'direct'),
  ('NUM.SCI_NOTATION', 'AERO.HSN.Q.3', 'partial'),
  ('NUM.ESTIMATION', 'AERO.HSN.Q.3', 'direct'),
  ('NUM.REAL_NUMBERS', 'AERO.HSN.RN.3', 'direct'),
  ('ALG.EXPRESSIONS', 'AERO.HSA.SSE.1-2', 'direct'),
  ('ALG.EQUIVALENT_EXPRESSIONS', 'AERO.HSA.SSE.2-3', 'direct'),
  ('ALG.REARRANGE_FORMULAS', 'AERO.HSA.CED.4', 'direct'),
  ('ALG.ABSOLUTE_VALUE', 'AERO.HSA.REI.3', 'partial'),
  ('ALG.ABSOLUTE_VALUE', 'AERO.HSF.IF.7', 'partial'),
  ('ALG.LINEAR_EQ_1VAR', 'AERO.HSA.REI.1', 'direct'),
  ('ALG.LINEAR_EQ_1VAR', 'AERO.HSA.REI.3', 'direct'),
  ('ALG.LINEAR_EQ_2VAR', 'AERO.HSA.CED.2', 'direct'),
  ('ALG.LINEAR_EQ_2VAR', 'AERO.HSA.REI.10', 'direct'),
  ('ALG.LINEAR_EQ_CONTEXT', 'AERO.HSA.CED.1-2', 'direct'),
  ('ALG.LINEAR_INEQUALITIES', 'AERO.HSA.REI.3', 'direct'),
  ('ALG.LINEAR_INEQUALITIES', 'AERO.HSA.REI.12', 'direct'),
  ('ALG.COMPOUND_INEQUALITIES', 'AERO.HSA.CED.3', 'direct'),
  ('ALG.COMPOUND_INEQUALITIES', 'AERO.HSA.REI.3', 'direct'),
  ('ALG.SYSTEMS_LINEAR', 'AERO.HSA.REI.5-6', 'direct'),
  ('ALG.SYSTEMS_CONTEXT', 'AERO.HSA.CED.2-3', 'direct'),
  ('ALG.SYSTEMS_CONTEXT', 'AERO.HSA.REI.6', 'direct'),
  ('ALG.NONLINEAR_SYSTEMS', 'AERO.HSA.REI.7', 'direct'),
  ('ALG.NONLINEAR_SYSTEMS', 'AERO.HSA.REI.11', 'direct'),
  ('ALG.EXPONENT_RULES', 'AERO.HSN.RN.1-2', 'direct'),
  ('ALG.RADICALS', 'AERO.HSN.RN.2', 'direct'),
  ('ALG.RATIONAL_EXPONENTS', 'AERO.HSN.RN.1-2', 'direct'),
  ('ALG.RADICAL_EQUATIONS', 'AERO.HSA.REI.2', 'direct'),
  ('ALG.POLYNOMIAL_OPS', 'AERO.HSA.APR.1', 'direct'),
  ('ALG.FACTORING', 'AERO.HSA.SSE.2-3', 'direct'),
  ('ALG.FACTORING', 'AERO.HSA.APR.3', 'direct'),
  ('ALG.POLYNOMIAL_DIVISION', 'AERO.HSA.APR.6', 'direct'),
  ('ALG.POLYNOMIAL_ZEROS', 'AERO.HSA.APR.2-3', 'direct'),
  ('ALG.BINOMIAL_THEOREM', 'AERO.HSA.APR.4-5', 'direct'),
  ('ALG.QUADRATIC_SOLVE', 'AERO.HSA.REI.4', 'direct'),
  ('ALG.QUADRATIC_DISCRIMINANT', 'AERO.HSA.REI.4', 'direct'),
  ('ALG.RATIONAL_EXPRESSIONS', 'AERO.HSA.APR.6-7', 'direct'),
  ('ALG.RATIONAL_EQUATIONS', 'AERO.HSA.REI.2', 'direct'),
  ('FUNC.CONCEPT', 'AERO.HSF.IF.1-2', 'direct'),
  ('FUNC.DOMAIN_RANGE', 'AERO.HSF.IF.5', 'direct'),
  ('FUNC.MULTIPLE_REPRESENTATIONS', 'AERO.HSF.IF.4', 'direct'),
  ('FUNC.MULTIPLE_REPRESENTATIONS', 'AERO.HSF.IF.9', 'direct'),
  ('FUNC.GRAPH_FEATURES', 'AERO.HSF.IF.4', 'direct'),
  ('FUNC.GRAPH_FEATURES', 'AERO.HSF.IF.7', 'direct'),
  ('FUNC.RATE_CHANGE', 'AERO.HSF.IF.6', 'direct'),
  ('FUNC.COMPARE', 'AERO.HSF.IF.9', 'direct'),
  ('FUNC.COMPARE', 'AERO.HSF.LE.1', 'direct'),
  ('FUNC.TRANSFORMATIONS', 'AERO.HSF.BF.3', 'direct'),
  ('FUNC.COMPOSITION', 'AERO.HSF.BF.1', 'direct'),
  ('FUNC.INVERSE', 'AERO.HSF.BF.4-5', 'direct'),
  ('FUNC.PIECEWISE', 'AERO.HSF.IF.7', 'direct'),
  ('FUNC.LINEAR', 'AERO.HSF.IF.7', 'direct'),
  ('FUNC.LINEAR', 'AERO.HSF.LE.1-2', 'direct'),
  ('FUNC.LINEAR_MODELING', 'AERO.HSF.LE.2', 'direct'),
  ('FUNC.LINEAR_MODELING', 'AERO.HSF.LE.5', 'direct'),
  ('FUNC.QUADRATIC', 'AERO.HSF.IF.7-8', 'direct'),
  ('FUNC.QUADRATIC_FORMS', 'AERO.HSF.IF.8', 'direct'),
  ('FUNC.QUADRATIC_FORMS', 'AERO.HSA.SSE.3', 'direct'),
  ('FUNC.QUADRATIC_MODELING', 'AERO.HSF.BF.1', 'direct'),
  ('FUNC.QUADRATIC_MODELING', 'AERO.HSF.IF.4', 'direct'),
  ('FUNC.POLYNOMIAL', 'AERO.HSF.IF.7', 'direct'),
  ('FUNC.POLYNOMIAL', 'AERO.HSA.APR.3', 'direct'),
  ('FUNC.RATIONAL', 'AERO.HSF.IF.7', 'direct'),
  ('FUNC.EXPONENTIAL', 'AERO.HSF.LE.1-3', 'direct'),
  ('FUNC.EXPONENTIAL_MODELING', 'AERO.HSF.LE.2', 'direct'),
  ('FUNC.EXPONENTIAL_MODELING', 'AERO.HSF.LE.5', 'direct'),
  ('FUNC.LOGARITHMIC', 'AERO.HSF.LE.4', 'direct'),
  ('FUNC.LOGARITHMIC', 'AERO.HSF.IF.7', 'direct'),
  ('GEO.ANGLES_LINES', 'AERO.HSG.CO.9', 'direct'),
  ('GEO.ANGLES_LINES', 'AERO.HSG.GPE.5', 'direct'),
  ('GEO.TRIANGLES', 'AERO.HSG.CO.10', 'direct'),
  ('GEO.CONGRUENCE', 'AERO.HSG.CO.6-8', 'direct'),
  ('GEO.SIMILARITY', 'AERO.HSG.SRT.1-5', 'direct'),
  ('GEO.PYTHAGOREAN', 'AERO.HSG.SRT.8', 'direct'),
  ('GEO.POLYGONS', 'AERO.HSG.CO.11', 'direct'),
  ('GEO.CIRCLES', 'AERO.HSG.C.1-3', 'direct'),
  ('GEO.CIRCLE_EQUATIONS', 'AERO.HSG.GPE.1', 'direct'),
  ('GEO.CIRCLE_MEASURE', 'AERO.HSG.C.5', 'direct'),
  ('GEO.CIRCLE_MEASURE', 'AERO.HSG.GMD.1', 'direct'),
  ('GEO.AREA', 'AERO.HSG.GMD.1', 'direct'),
  ('GEO.AREA', 'AERO.HSG.MG.1', 'direct'),
  ('GEO.SURFACE_AREA', 'AERO.HSG.GMD.1', 'direct'),
  ('GEO.SURFACE_AREA', 'AERO.HSG.MG.1', 'direct'),
  ('GEO.VOLUME', 'AERO.HSG.GMD.1-3', 'direct'),
  ('GEO.COORDINATE', 'AERO.HSG.GPE.4-7', 'direct'),
  ('GEO.TRANSFORMATIONS', 'AERO.HSG.CO.2-5', 'direct'),
  ('GEO.GEOMETRIC_REASONING', 'AERO.HSG.CO.9-11', 'direct'),
  ('GEO.GEOMETRIC_REASONING', 'AERO.HSG.SRT.4', 'direct'),
  ('GEO.MODELING', 'AERO.HSG.MG.1-3', 'direct'),
  ('TRIG.RIGHT_TRIANGLE', 'AERO.HSG.SRT.6-8', 'direct'),
  ('TRIG.SPECIAL_TRIANGLES', 'AERO.HSF.TF.3', 'direct'),
  ('TRIG.SPECIAL_TRIANGLES', 'AERO.HSG.SRT.8', 'direct'),
  ('TRIG.RADIANS', 'AERO.HSF.TF.1', 'direct'),
  ('TRIG.UNIT_CIRCLE', 'AERO.HSF.TF.2-4', 'direct'),
  ('TRIG.GRAPHS', 'AERO.HSF.IF.7', 'direct'),
  ('TRIG.GRAPHS', 'AERO.HSF.TF.5', 'direct'),
  ('TRIG.TRANSFORMATIONS', 'AERO.HSF.BF.3', 'direct'),
  ('TRIG.TRANSFORMATIONS', 'AERO.HSF.TF.5', 'direct'),
  ('TRIG.INVERSE', 'AERO.HSF.TF.6-7', 'direct'),
  ('TRIG.IDENTITIES', 'AERO.HSF.TF.8-9', 'direct'),
  ('TRIG.EQUATIONS', 'AERO.HSF.TF.7-9', 'direct'),
  ('TRIG.LAW_SINES_COSINES', 'AERO.HSG.SRT.9-11', 'direct'),
  ('TRIG.MODELING', 'AERO.HSF.TF.5', 'direct'),
  ('STAT.DATA_DISPLAYS', 'AERO.HSS.ID.1', 'direct'),
  ('STAT.CENTER', 'AERO.HSS.ID.2', 'direct'),
  ('STAT.VARIABILITY', 'AERO.HSS.ID.2', 'direct'),
  ('STAT.PERCENTILES', 'AERO.HSS.ID.1-2', 'partial'),
  ('STAT.DISTRIBUTIONS', 'AERO.HSS.ID.1-3', 'direct'),
  ('STAT.NORMAL_DISTRIBUTION', 'AERO.HSS.ID.4', 'direct'),
  ('STAT.SCATTERPLOTS', 'AERO.HSS.ID.6', 'direct'),
  ('STAT.REGRESSION', 'AERO.HSS.ID.6-9', 'direct'),
  ('STAT.TWO_WAY_TABLES', 'AERO.HSS.ID.5', 'direct'),
  ('STAT.TWO_WAY_TABLES', 'AERO.HSS.CP.4', 'direct'),
  ('STAT.SET_OPERATIONS', 'AERO.HSS.CP.1', 'direct'),
  ('PROB.BASIC', 'AERO.HSS.CP.1', 'direct'),
  ('PROB.COMPOUND', 'AERO.HSS.CP.7-8', 'direct'),
  ('PROB.CONDITIONAL', 'AERO.HSS.CP.3-6', 'direct'),
  ('PROB.INDEPENDENCE', 'AERO.HSS.CP.2-5', 'direct'),
  ('PROB.COUNTING_PRINCIPLES', 'AERO.HSS.CP.9', 'partial'),
  ('PROB.PERM_COMB', 'AERO.HSS.CP.9', 'direct'),
  ('PROB.EXPECTED_VALUE', 'AERO.HSS.MD.1-3', 'direct'),
  ('STAT.SAMPLING', 'AERO.HSS.IC.1-3', 'direct'),
  ('STAT.MARGIN_ERROR', 'AERO.HSS.IC.4', 'direct'),
  ('STAT.INFERENCE', 'AERO.HSS.IC.1', 'direct'),
  ('STAT.INFERENCE', 'AERO.HSS.IC.4-5', 'direct'),
  ('STAT.STUDY_DESIGN', 'AERO.HSS.IC.3', 'direct'),
  ('STAT.STUDY_DESIGN', 'AERO.HSS.IC.5-6', 'direct'),
  ('PRE.SEQUENCES', 'AERO.HSF.BF.2', 'direct'),
  ('PRE.SEQUENCES', 'AERO.HSA.SSE.4', 'direct'),
  ('PRE.SERIES', 'AERO.HSA.SSE.4', 'direct'),
  ('PRE.RECURSIVE', 'AERO.HSF.BF.2', 'direct'),
  ('PRE.COMPLEX_ARITHMETIC', 'AERO.HSN.CN.1-3', 'direct'),
  ('PRE.COMPLEX_PLANE_ROOTS', 'AERO.HSN.CN.4-9', 'direct'),
  ('PRE.POLAR', NULL, 'extension'),
  ('PRE.VECTORS', 'AERO.HSN.VM.1-5', 'direct'),
  ('PRE.MATRICES', 'AERO.HSN.VM.6-12', 'direct'),
  ('PRE.MATRICES', 'AERO.HSA.REI.8-9', 'direct'),
  ('PRE.PARAMETRIC', NULL, 'extension'),
  ('PRE.CONICS', 'AERO.HSG.GPE.2-3', 'direct'),
  ('PRE.LIMIT_INTUITION', NULL, 'extension'),
  ('CALC.LIMITS', NULL, 'extension'),
  ('CALC.CONTINUITY', NULL, 'extension'),
  ('CALC.DERIVATIVE_CONCEPT', NULL, 'extension'),
  ('CALC.DERIVATIVE_RULES', NULL, 'extension'),
  ('CALC.DERIVATIVE_FUNCTIONS', NULL, 'extension'),
  ('CALC.DERIVATIVE_APPLICATIONS', NULL, 'extension'),
  ('CALC.GRAPH_ANALYSIS', NULL, 'extension'),
  ('CALC.INTEGRAL_CONCEPT', NULL, 'extension'),
  ('CALC.INTEGRATION', NULL, 'extension'),
  ('CALC.FTC', NULL, 'extension')
) as seed(skill_code, aero_code, mapping_status)
join public.skills skill on skill.code = seed.skill_code;

insert into public.skill_sat_mappings (skill_id, sat_domain, sat_skill, mapping_status)
select skill.id, seed.sat_domain, seed.sat_skill, seed.mapping_status
from (values
  ('NUM.ORDER_OPS', NULL, NULL, 'supporting'),
  ('NUM.INTEGER_OPS', NULL, NULL, 'supporting'),
  ('NUM.FRACTIONS', 'Problem-Solving and Data Analysis', 'Ratios, rates, proportional relationships, and units', 'supporting'),
  ('NUM.DECIMALS', 'Problem-Solving and Data Analysis', 'Percentages', 'supporting'),
  ('NUM.RATIOS_RATES', 'Problem-Solving and Data Analysis', 'Ratios, rates, proportional relationships, and units', 'direct'),
  ('NUM.PROPORTIONS', 'Problem-Solving and Data Analysis', 'Ratios, rates, proportional relationships, and units', 'direct'),
  ('NUM.PERCENT', 'Problem-Solving and Data Analysis', 'Percentages', 'direct'),
  ('NUM.UNITS', 'Problem-Solving and Data Analysis', 'Ratios, rates, proportional relationships, and units', 'direct'),
  ('NUM.SCI_NOTATION', 'Advanced Math', 'Equivalent expressions', 'supporting'),
  ('NUM.ESTIMATION', 'Problem-Solving and Data Analysis', 'Ratios, rates, proportional relationships, and units', 'supporting'),
  ('NUM.REAL_NUMBERS', 'Advanced Math', 'Equivalent expressions', 'supporting'),
  ('ALG.EXPRESSIONS', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.EQUIVALENT_EXPRESSIONS', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.REARRANGE_FORMULAS', 'Algebra', 'Linear equations in one variable', 'supporting'),
  ('ALG.ABSOLUTE_VALUE', 'Advanced Math', 'Nonlinear equations in one variable', 'direct'),
  ('ALG.LINEAR_EQ_1VAR', 'Algebra', 'Linear equations in one variable', 'direct'),
  ('ALG.LINEAR_EQ_2VAR', 'Algebra', 'Linear equations in two variables', 'direct'),
  ('ALG.LINEAR_EQ_CONTEXT', 'Algebra', 'Linear equations in one variable', 'direct'),
  ('ALG.LINEAR_EQ_CONTEXT', 'Algebra', 'Linear equations in two variables', 'direct'),
  ('ALG.LINEAR_INEQUALITIES', 'Algebra', 'Linear inequalities in one or two variables', 'direct'),
  ('ALG.COMPOUND_INEQUALITIES', 'Algebra', 'Linear inequalities in one or two variables', 'supporting'),
  ('ALG.SYSTEMS_LINEAR', 'Algebra', 'Systems of two linear equations in two variables', 'direct'),
  ('ALG.SYSTEMS_CONTEXT', 'Algebra', 'Systems of two linear equations in two variables', 'direct'),
  ('ALG.NONLINEAR_SYSTEMS', 'Advanced Math', 'Systems of equations in two variables', 'direct'),
  ('ALG.EXPONENT_RULES', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.RADICALS', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.RADICALS', 'Advanced Math', 'Nonlinear equations in one variable', 'direct'),
  ('ALG.RATIONAL_EXPONENTS', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.RADICAL_EQUATIONS', 'Advanced Math', 'Nonlinear equations in one variable', 'direct'),
  ('ALG.POLYNOMIAL_OPS', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.FACTORING', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.POLYNOMIAL_DIVISION', 'Advanced Math', 'Equivalent expressions', 'supporting'),
  ('ALG.POLYNOMIAL_ZEROS', 'Advanced Math', 'Nonlinear equations in one variable', 'direct'),
  ('ALG.POLYNOMIAL_ZEROS', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('ALG.BINOMIAL_THEOREM', NULL, NULL, 'not_assessed'),
  ('ALG.QUADRATIC_SOLVE', 'Advanced Math', 'Nonlinear equations in one variable', 'direct'),
  ('ALG.QUADRATIC_DISCRIMINANT', 'Advanced Math', 'Nonlinear equations in one variable', 'supporting'),
  ('ALG.RATIONAL_EXPRESSIONS', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('ALG.RATIONAL_EQUATIONS', 'Advanced Math', 'Nonlinear equations in one variable', 'direct'),
  ('FUNC.CONCEPT', 'Algebra', 'Linear functions', 'supporting'),
  ('FUNC.DOMAIN_RANGE', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.MULTIPLE_REPRESENTATIONS', 'Algebra', 'Linear functions', 'direct'),
  ('FUNC.GRAPH_FEATURES', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.RATE_CHANGE', 'Algebra', 'Linear functions', 'direct'),
  ('FUNC.COMPARE', 'Advanced Math', 'Nonlinear functions', 'supporting'),
  ('FUNC.TRANSFORMATIONS', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.COMPOSITION', 'Advanced Math', 'Nonlinear functions', 'supporting'),
  ('FUNC.INVERSE', 'Advanced Math', 'Nonlinear functions', 'supporting'),
  ('FUNC.PIECEWISE', 'Advanced Math', 'Nonlinear functions', 'supporting'),
  ('FUNC.LINEAR', 'Algebra', 'Linear functions', 'direct'),
  ('FUNC.LINEAR_MODELING', 'Algebra', 'Linear functions', 'direct'),
  ('FUNC.QUADRATIC', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.QUADRATIC_FORMS', 'Advanced Math', 'Equivalent expressions', 'direct'),
  ('FUNC.QUADRATIC_FORMS', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.QUADRATIC_MODELING', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.POLYNOMIAL', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.RATIONAL', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.EXPONENTIAL', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.EXPONENTIAL_MODELING', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('FUNC.LOGARITHMIC', 'Advanced Math', 'Nonlinear equations in one variable', 'direct'),
  ('FUNC.LOGARITHMIC', 'Advanced Math', 'Nonlinear functions', 'direct'),
  ('GEO.ANGLES_LINES', 'Geometry and Trigonometry', 'Lines, angles, and triangles', 'direct'),
  ('GEO.TRIANGLES', 'Geometry and Trigonometry', 'Lines, angles, and triangles', 'direct'),
  ('GEO.CONGRUENCE', 'Geometry and Trigonometry', 'Lines, angles, and triangles', 'supporting'),
  ('GEO.SIMILARITY', 'Geometry and Trigonometry', 'Lines, angles, and triangles', 'direct'),
  ('GEO.PYTHAGOREAN', 'Geometry and Trigonometry', 'Lines, angles, and triangles', 'direct'),
  ('GEO.POLYGONS', 'Geometry and Trigonometry', 'Lines, angles, and triangles', 'supporting'),
  ('GEO.CIRCLES', 'Geometry and Trigonometry', 'Circles', 'direct'),
  ('GEO.CIRCLE_EQUATIONS', 'Geometry and Trigonometry', 'Circles', 'direct'),
  ('GEO.CIRCLE_MEASURE', 'Geometry and Trigonometry', 'Circles', 'direct'),
  ('GEO.AREA', 'Geometry and Trigonometry', 'Area and volume', 'direct'),
  ('GEO.SURFACE_AREA', 'Geometry and Trigonometry', 'Area and volume', 'direct'),
  ('GEO.VOLUME', 'Geometry and Trigonometry', 'Area and volume', 'direct'),
  ('GEO.COORDINATE', 'Geometry and Trigonometry', 'Lines, angles, and triangles', 'supporting'),
  ('GEO.TRANSFORMATIONS', NULL, NULL, 'not_assessed'),
  ('GEO.GEOMETRIC_REASONING', NULL, NULL, 'supporting'),
  ('GEO.MODELING', 'Geometry and Trigonometry', 'Area and volume', 'supporting'),
  ('TRIG.RIGHT_TRIANGLE', 'Geometry and Trigonometry', 'Right triangles and trigonometry', 'direct'),
  ('TRIG.SPECIAL_TRIANGLES', 'Geometry and Trigonometry', 'Right triangles and trigonometry', 'direct'),
  ('TRIG.RADIANS', 'Geometry and Trigonometry', 'Circles', 'supporting'),
  ('TRIG.RADIANS', 'Geometry and Trigonometry', 'Right triangles and trigonometry', 'supporting'),
  ('TRIG.UNIT_CIRCLE', 'Geometry and Trigonometry', 'Right triangles and trigonometry', 'supporting'),
  ('TRIG.GRAPHS', NULL, NULL, 'not_assessed'),
  ('TRIG.TRANSFORMATIONS', NULL, NULL, 'not_assessed'),
  ('TRIG.INVERSE', 'Geometry and Trigonometry', 'Right triangles and trigonometry', 'supporting'),
  ('TRIG.IDENTITIES', NULL, NULL, 'not_assessed'),
  ('TRIG.EQUATIONS', NULL, NULL, 'not_assessed'),
  ('TRIG.LAW_SINES_COSINES', NULL, NULL, 'not_assessed'),
  ('TRIG.MODELING', NULL, NULL, 'not_assessed'),
  ('STAT.DATA_DISPLAYS', 'Problem-Solving and Data Analysis', 'One-variable data: Distributions and measures of center and spread', 'direct'),
  ('STAT.CENTER', 'Problem-Solving and Data Analysis', 'One-variable data: Distributions and measures of center and spread', 'direct'),
  ('STAT.VARIABILITY', 'Problem-Solving and Data Analysis', 'One-variable data: Distributions and measures of center and spread', 'direct'),
  ('STAT.PERCENTILES', 'Problem-Solving and Data Analysis', 'One-variable data: Distributions and measures of center and spread', 'supporting'),
  ('STAT.DISTRIBUTIONS', 'Problem-Solving and Data Analysis', 'One-variable data: Distributions and measures of center and spread', 'direct'),
  ('STAT.NORMAL_DISTRIBUTION', NULL, NULL, 'not_assessed'),
  ('STAT.SCATTERPLOTS', 'Problem-Solving and Data Analysis', 'Two-variable data: Models and scatterplots', 'direct'),
  ('STAT.REGRESSION', 'Problem-Solving and Data Analysis', 'Two-variable data: Models and scatterplots', 'direct'),
  ('STAT.TWO_WAY_TABLES', 'Problem-Solving and Data Analysis', 'Probability and conditional probability', 'direct'),
  ('STAT.SET_OPERATIONS', 'Problem-Solving and Data Analysis', 'Probability and conditional probability', 'supporting'),
  ('PROB.BASIC', 'Problem-Solving and Data Analysis', 'Probability and conditional probability', 'direct'),
  ('PROB.COMPOUND', 'Problem-Solving and Data Analysis', 'Probability and conditional probability', 'direct'),
  ('PROB.CONDITIONAL', 'Problem-Solving and Data Analysis', 'Probability and conditional probability', 'direct'),
  ('PROB.INDEPENDENCE', 'Problem-Solving and Data Analysis', 'Probability and conditional probability', 'direct'),
  ('PROB.COUNTING_PRINCIPLES', NULL, NULL, 'not_assessed'),
  ('PROB.PERM_COMB', NULL, NULL, 'not_assessed'),
  ('PROB.EXPECTED_VALUE', NULL, NULL, 'not_assessed'),
  ('STAT.SAMPLING', 'Problem-Solving and Data Analysis', 'Inference from sample statistics and margin of error', 'direct'),
  ('STAT.MARGIN_ERROR', 'Problem-Solving and Data Analysis', 'Inference from sample statistics and margin of error', 'direct'),
  ('STAT.INFERENCE', 'Problem-Solving and Data Analysis', 'Inference from sample statistics and margin of error', 'direct'),
  ('STAT.STUDY_DESIGN', 'Problem-Solving and Data Analysis', 'Evaluating statistical claims: Observational studies and experiments', 'direct'),
  ('PRE.SEQUENCES', 'Advanced Math', 'Nonlinear functions', 'supporting'),
  ('PRE.SERIES', NULL, NULL, 'not_assessed'),
  ('PRE.RECURSIVE', NULL, NULL, 'not_assessed'),
  ('PRE.COMPLEX_ARITHMETIC', 'Advanced Math', 'Nonlinear equations in one variable', 'supporting'),
  ('PRE.COMPLEX_PLANE_ROOTS', NULL, NULL, 'not_assessed'),
  ('PRE.POLAR', NULL, NULL, 'not_assessed'),
  ('PRE.VECTORS', NULL, NULL, 'not_assessed'),
  ('PRE.MATRICES', NULL, NULL, 'not_assessed'),
  ('PRE.PARAMETRIC', NULL, NULL, 'not_assessed'),
  ('PRE.CONICS', 'Advanced Math', 'Nonlinear functions', 'supporting'),
  ('PRE.LIMIT_INTUITION', NULL, NULL, 'not_assessed'),
  ('CALC.LIMITS', NULL, NULL, 'not_assessed'),
  ('CALC.CONTINUITY', NULL, NULL, 'not_assessed'),
  ('CALC.DERIVATIVE_CONCEPT', NULL, NULL, 'not_assessed'),
  ('CALC.DERIVATIVE_RULES', NULL, NULL, 'not_assessed'),
  ('CALC.DERIVATIVE_FUNCTIONS', NULL, NULL, 'not_assessed'),
  ('CALC.DERIVATIVE_APPLICATIONS', NULL, NULL, 'not_assessed'),
  ('CALC.GRAPH_ANALYSIS', NULL, NULL, 'not_assessed'),
  ('CALC.INTEGRAL_CONCEPT', NULL, NULL, 'not_assessed'),
  ('CALC.INTEGRATION', NULL, NULL, 'not_assessed'),
  ('CALC.FTC', NULL, NULL, 'not_assessed')
) as seed(skill_code, sat_domain, sat_skill, mapping_status)
join public.skills skill on skill.code = seed.skill_code;

insert into public.skill_icfes_mappings (skill_id, category, content_type, mapping_status)
select skill.id, seed.category, seed.content_type, seed.mapping_status
from (values
  ('NUM.ORDER_OPS', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.INTEGER_OPS', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.FRACTIONS', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.DECIMALS', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.RATIOS_RATES', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.PROPORTIONS', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.PERCENT', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.UNITS', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.SCI_NOTATION', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.ESTIMATION', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('NUM.REAL_NUMBERS', 'Álgebra y cálculo', 'No genérico', 'supporting'),
  ('ALG.EXPRESSIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.EQUIVALENT_EXPRESSIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.REARRANGE_FORMULAS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.ABSOLUTE_VALUE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.LINEAR_EQ_1VAR', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('ALG.LINEAR_EQ_2VAR', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('ALG.LINEAR_EQ_CONTEXT', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('ALG.LINEAR_INEQUALITIES', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('ALG.COMPOUND_INEQUALITIES', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.SYSTEMS_LINEAR', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('ALG.SYSTEMS_CONTEXT', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('ALG.NONLINEAR_SYSTEMS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.EXPONENT_RULES', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('ALG.RADICALS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.RATIONAL_EXPONENTS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.RADICAL_EQUATIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.POLYNOMIAL_OPS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.FACTORING', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.POLYNOMIAL_DIVISION', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.POLYNOMIAL_ZEROS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.BINOMIAL_THEOREM', 'Álgebra y cálculo', 'No genérico', 'supporting'),
  ('ALG.QUADRATIC_SOLVE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.QUADRATIC_DISCRIMINANT', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.RATIONAL_EXPRESSIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('ALG.RATIONAL_EQUATIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.CONCEPT', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.DOMAIN_RANGE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.MULTIPLE_REPRESENTATIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.GRAPH_FEATURES', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.RATE_CHANGE', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('FUNC.COMPARE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.TRANSFORMATIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.COMPOSITION', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.INVERSE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.PIECEWISE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.LINEAR', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('FUNC.LINEAR_MODELING', 'Álgebra y cálculo', 'Genérico', 'direct'),
  ('FUNC.QUADRATIC', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.QUADRATIC_FORMS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.QUADRATIC_MODELING', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.POLYNOMIAL', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.RATIONAL', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.EXPONENTIAL', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.EXPONENTIAL_MODELING', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('FUNC.LOGARITHMIC', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('GEO.ANGLES_LINES', 'Geometría', 'Genérico', 'direct'),
  ('GEO.TRIANGLES', 'Geometría', 'Genérico', 'direct'),
  ('GEO.CONGRUENCE', 'Geometría', 'No genérico', 'direct'),
  ('GEO.SIMILARITY', 'Geometría', 'No genérico', 'direct'),
  ('GEO.PYTHAGOREAN', 'Geometría', 'No genérico', 'direct'),
  ('GEO.POLYGONS', 'Geometría', 'Mixto', 'direct'),
  ('GEO.CIRCLES', 'Geometría', 'Genérico', 'direct'),
  ('GEO.CIRCLE_EQUATIONS', 'Geometría', 'Genérico', 'direct'),
  ('GEO.CIRCLE_MEASURE', 'Geometría', 'Genérico', 'direct'),
  ('GEO.AREA', 'Geometría', 'Genérico', 'direct'),
  ('GEO.SURFACE_AREA', 'Geometría', 'Mixto', 'direct'),
  ('GEO.VOLUME', 'Geometría', 'Genérico', 'direct'),
  ('GEO.COORDINATE', 'Geometría', 'Genérico', 'direct'),
  ('GEO.TRANSFORMATIONS', 'Geometría', 'No genérico', 'direct'),
  ('GEO.GEOMETRIC_REASONING', 'Geometría', 'No genérico', 'direct'),
  ('GEO.MODELING', 'Geometría', 'Genérico', 'direct'),
  ('TRIG.RIGHT_TRIANGLE', 'Geometría', 'No genérico', 'direct'),
  ('TRIG.SPECIAL_TRIANGLES', 'Geometría', 'No genérico', 'supporting'),
  ('TRIG.RADIANS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('TRIG.UNIT_CIRCLE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('TRIG.GRAPHS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('TRIG.TRANSFORMATIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('TRIG.INVERSE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('TRIG.IDENTITIES', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('TRIG.EQUATIONS', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('TRIG.LAW_SINES_COSINES', 'Geometría', 'No genérico', 'supporting'),
  ('TRIG.MODELING', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('STAT.DATA_DISPLAYS', 'Estadística', 'Genérico', 'direct'),
  ('STAT.CENTER', 'Estadística', 'Mixto', 'direct'),
  ('STAT.VARIABILITY', 'Estadística', 'Mixto', 'direct'),
  ('STAT.PERCENTILES', 'Estadística', 'No genérico', 'direct'),
  ('STAT.DISTRIBUTIONS', 'Estadística', 'Mixto', 'direct'),
  ('STAT.NORMAL_DISTRIBUTION', 'Estadística', 'No genérico', 'supporting'),
  ('STAT.SCATTERPLOTS', 'Estadística', 'No genérico', 'direct'),
  ('STAT.REGRESSION', 'Estadística', 'No genérico', 'direct'),
  ('STAT.TWO_WAY_TABLES', 'Estadística', 'Genérico', 'direct'),
  ('STAT.SET_OPERATIONS', 'Estadística', 'Genérico', 'direct'),
  ('PROB.BASIC', 'Estadística', 'Genérico', 'direct'),
  ('PROB.COMPOUND', 'Estadística', 'Genérico', 'direct'),
  ('PROB.CONDITIONAL', 'Estadística', 'Genérico', 'direct'),
  ('PROB.INDEPENDENCE', 'Estadística', 'Genérico', 'direct'),
  ('PROB.COUNTING_PRINCIPLES', 'Estadística', 'Genérico', 'direct'),
  ('PROB.PERM_COMB', 'Estadística', 'No genérico', 'direct'),
  ('PROB.EXPECTED_VALUE', 'Estadística', 'No genérico', 'supporting'),
  ('STAT.SAMPLING', 'Estadística', 'Genérico', 'direct'),
  ('STAT.MARGIN_ERROR', 'Estadística', 'No genérico', 'direct'),
  ('STAT.INFERENCE', 'Estadística', 'Genérico', 'direct'),
  ('STAT.STUDY_DESIGN', 'Estadística', 'Genérico', 'direct'),
  ('PRE.SEQUENCES', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('PRE.SERIES', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('PRE.RECURSIVE', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('PRE.COMPLEX_ARITHMETIC', 'Álgebra y cálculo', 'No genérico', 'supporting'),
  ('PRE.COMPLEX_PLANE_ROOTS', 'Álgebra y cálculo', 'No genérico', 'supporting'),
  ('PRE.POLAR', 'Geometría', 'No genérico', 'direct'),
  ('PRE.VECTORS', 'Geometría', 'No genérico', 'supporting'),
  ('PRE.MATRICES', 'Álgebra y cálculo', 'No genérico', 'supporting'),
  ('PRE.PARAMETRIC', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('PRE.CONICS', 'Geometría', 'No genérico', 'direct'),
  ('PRE.LIMIT_INTUITION', 'Álgebra y cálculo', 'No genérico', 'direct'),
  ('CALC.LIMITS', 'Álgebra y cálculo', 'No genérico', 'supporting'),
  ('CALC.CONTINUITY', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.DERIVATIVE_CONCEPT', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.DERIVATIVE_RULES', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.DERIVATIVE_FUNCTIONS', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.DERIVATIVE_APPLICATIONS', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.GRAPH_ANALYSIS', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.INTEGRAL_CONCEPT', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.INTEGRATION', 'Álgebra y cálculo', 'No genérico', 'not_explicit'),
  ('CALC.FTC', 'Álgebra y cálculo', 'No genérico', 'not_explicit')
) as seed(skill_code, category, content_type, mapping_status)
join public.skills skill on skill.code = seed.skill_code;

commit;
