import Link from "next/link";
import { notFound } from "next/navigation";
import { addStudentToClass, removeStudentFromClass, updateClass } from "../../actions";
import { requireTeacher } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type Student = { id: string; full_name: string | null; email: string | null; grade_level: number | null };
export default async function ClassDetailPage({ params, searchParams }: PageProps<"/teacher/classes/[id]">) {
  const teacher = await requireTeacher(); const { id } = await params; const messages = await searchParams; const supabase = await createClient(); const { data: classroom, error: classroomError } = await supabase.from("classes").select("id, name, grade_level, academic_year, teacher_id").eq("id", id).maybeSingle(); if (classroomError || !classroom || classroom.teacher_id !== teacher.id) notFound();
  const [{ data: members }, { data: allStudents }] = await Promise.all([supabase.from("class_members").select("student_id").eq("class_id", id), supabase.from("profiles").select("id, full_name, email, grade_level").eq("role", "student").order("full_name")]);
  const studentsById = new Map((allStudents as Student[] | null ?? []).map((student) => [student.id, student])); const memberIds = new Set(members?.map(({ student_id }) => student_id) ?? []); const enrolled = [...memberIds].map((studentId) => studentsById.get(studentId)).filter((student): student is Student => Boolean(student)); const available = (allStudents as Student[] | null ?? []).filter((student) => !memberIds.has(student.id));
  return <main className="teacher-main"><Link className="back-link" href="/teacher/classes">← All classes</Link><section className="page-heading class-heading"><div><p className="eyebrow">Grade {classroom.grade_level} · {classroom.academic_year}</p><h1>{classroom.name}</h1><p>{enrolled.length} {enrolled.length === 1 ? "student" : "students"} currently assigned.</p></div></section>{messages.error && <p className="notice notice-error" role="alert">{messages.error}</p>}{messages.success && <p className="notice notice-success">{messages.success}</p>}<div className="teacher-two-column class-detail-grid"><section className="teacher-section"><div className="section-row"><h2>Current students</h2><span className="muted-count">{enrolled.length}</span></div>{enrolled.length ? <div className="student-list">{enrolled.map((student) => <div key={student.id}><div><strong>{student.full_name || "Unnamed student"}</strong><span>{student.email} · Grade {student.grade_level ?? "—"}</span></div><form action={removeStudentFromClass}><input name="class_id" type="hidden" value={id} /><input name="student_id" type="hidden" value={student.id} /><button className="text-button" type="submit">Remove</button></form></div>)}</div> : <div className="compact-empty"><h3>No students assigned.</h3><p>Add an existing student account below.</p></div>}</section><aside className="teacher-form-card"><p className="eyebrow">Enrollment</p><h2>Add a student</h2>{available.length ? <form action={addStudentToClass}><input name="class_id" type="hidden" value={id} /><label>Existing student<select name="student_id" defaultValue=""><option disabled value="">Choose a student</option>{available.map((student) => <option key={student.id} value={student.id}>{student.full_name || student.email} · Grade {student.grade_level ?? "—"}</option>)}</select></label><button className="teacher-button" type="submit">Add student <span>→</span></button></form> : <p className="form-note">No other student accounts are available to add.</p>}<hr /><p className="eyebrow">Class details</p><form action={updateClass}><input name="class_id" type="hidden" value={id} /><label>Class name<input defaultValue={classroom.name} name="name" required /></label><label>Grade<select defaultValue={classroom.grade_level} name="grade_level"><option value="11">Grade 11</option><option value="12">Grade 12</option></select></label><label>Academic year<input defaultValue={classroom.academic_year} name="academic_year" required /></label><button className="secondary-button" type="submit">Save class details</button></form></aside></div></main>;
}
