import Link from "next/link";
import { requireStudent } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { progressByDomain, progressPercent, progressStatus, type SkillProgress } from "@/lib/skill-progress";

export default async function StudentProgressPage() {
  const student = await requireStudent(); const supabase = await createClient(); const { data } = await supabase.rpc("get_student_skill_progress", { p_student_id: student.id }); const progress = (data ?? []) as SkillProgress[];
  const statuses = progress.map(progressStatus); const summary = { evidence: progress.length, strong: statuses.filter((status) => status === "Strong").length, developing: statuses.filter((status) => status === "Developing").length, needsWork: statuses.filter((status) => status === "Needs work").length };
  return <main className="student-page"><div className="student-container"><Link className="back-link" href="/student">← Your assignments</Link><section className="student-intro"><p className="eyebrow">Evidence-based progress</p><h1>Your skill progress</h1><p>Status is based on submitted assessment evidence. Skills need at least three scored questions before a performance label is assigned.</p></section>{progress.length ? <><section className="progress-summary"><article><span>Skills with evidence</span><strong>{summary.evidence}</strong></article><article><span>Strong</span><strong>{summary.strong}</strong></article><article><span>Developing</span><strong>{summary.developing}</strong></article><article><span>Needs work</span><strong>{summary.needsWork}</strong></article></section><section className="progress-domains">{progressByDomain(progress).map(([domain, skills], index) => <details key={domain} open={index === 0}><summary>{domain}<span>{skills.length} skills</span></summary><div>{skills.map((skill) => { const status = progressStatus(skill); const percent = progressPercent(skill); return <article className="skill-progress-row" key={skill.skill_code}><div><strong>{skill.skill_name}</strong><small>{skill.correct_evidence}/{skill.attempted_evidence} correct · {skill.earned_points}/{skill.possible_points} points</small></div><div className="skill-progress-score"><b>{percent}%</b><span className={`progress-status ${status.toLowerCase().replaceAll(" ", "-")}`}>{status}</span><i><em style={{ width: `${percent}%` }} /></i></div></article>; })}</div></details>)}</section></> : <section className="student-results"><h2>No submitted assessment evidence yet.</h2><p>Complete an assessment to begin building a transparent skill record.</p></section>}</div></main>;
}
