import Link from "next/link";
import AssignmentDue from "@/app/components/assignment-due";
import LogoutButton from "./logout-button";
import { requireStudent } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

export default async function StudentPage() {
  const profile = await requireStudent(); const supabase = await createClient(); const [{ data: assignments }, { data: attempts }] = await Promise.all([supabase.from("assignments").select("id, title, description, kind, status, due_at, duration_minutes, max_attempts, show_score_after_submit").in("status", ["published", "closed"]).order("due_at", { ascending: true, nullsFirst: false }), supabase.from("attempts").select("assignment_id, status, score, max_score, attempt_number").eq("student_id", profile.id)]);
  const attemptsByAssignment = new Map<string, typeof attempts>(); attempts?.forEach((attempt) => attemptsByAssignment.set(attempt.assignment_id, [...(attemptsByAssignment.get(attempt.assignment_id) ?? []), attempt]));
  return <main className="student-page"><div className="student-container"><header className="student-header"><div className="auth-brand"><span className="brand-mark" aria-hidden="true">∑</span>Jaguar Math</div><div className="student-header-actions"><Link href="/student/progress">Progress</Link><LogoutButton /></div></header><section className="student-intro"><p className="eyebrow">Student space</p><h1>Welcome, {profile.full_name?.split(" ")[0] || "student"}.</h1><p>{profile.email}</p></section><section className="student-assignment-list"><div className="section-row"><div><p className="eyebrow">Assigned work</p><h2>Your assessments</h2></div><span className="muted-count">{assignments?.length ?? 0} assigned</span></div>{assignments?.length ? assignments.map((assignment) => { const assignmentAttempts = attemptsByAssignment.get(assignment.id) ?? []; const active = assignmentAttempts.find((attempt) => attempt.status === "in_progress"); const completed = assignmentAttempts.filter((attempt) => attempt.status === "submitted").at(-1); return <Link className="student-assignment" href={`/student/assignments/${assignment.id}`} key={assignment.id}><div><span>{assignment.kind}</span><strong>{assignment.title}</strong><small>{assignment.description || "Open to begin."}</small><AssignmentDue dueAt={assignment.due_at} status={assignment.status} /></div><b>{assignment.status === "closed" ? "Closed" : active ? "Continue →" : completed ? (assignment.show_score_after_submit ? `${completed.score ?? 0}/${completed.max_score ?? 0} →` : "Submitted →") : "Start →"}</b></Link>; }) : <div className="student-empty"><h3>No assignments available.</h3><p>Your teacher’s published work will appear here.</p></div>}</section></div></main>;
}
