import Link from "next/link";
import { notFound } from "next/navigation";
import { duplicateAssignment, publishAssignment, updateAssignment } from "../../assignment-actions";
import AssignmentResultsOverview from "../assignment-results-overview";
import DraftQuestionSet, { type DraftQuestion } from "../draft-question-set";
import DuplicateButton from "../duplicate-button";
import AssignmentDue from "@/app/components/assignment-due";
import DueDateInput from "@/app/components/due-date-input";
import MathText from "@/app/components/math-text";
import { requireTeacher } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import LifecycleControls from "../lifecycle-controls";
import AssessmentPolicySettings from "../assessment-policy-settings";
import ResultReleaseControls from "../result-release-controls";

type AssignmentPageProps = { params: Promise<{ id: string }>; searchParams: Promise<{ classId?: string; error?: string; success?: string }> };
type QuestionRow = { id: string; prompt: string; type: DraftQuestion["type"]; options: DraftQuestion["options"]; difficulty: number; icfes_competency: string | null };
type QuestionKey = { question_id: string; correct_answer: string; numeric_tolerance: number; explanation: string | null };
type QuestionSkill = { question_id: string; weight: number; is_primary: boolean; skills: { code: string; name: string } | { code: string; name: string }[] | null };
type QuestionVariant = { slot_position: number; variant_index: number };

export default async function AssignmentDetailPage({ params, searchParams }: AssignmentPageProps) {
  const teacher = await requireTeacher(); const { id } = await params; const messages = await searchParams; const supabase = await createClient();
  const { data: assignment, error } = await supabase.from("assignments").select("id, title, description, kind, status, due_at, duration_minutes, max_attempts, show_score_after_submit, show_answers_after_submit, show_feedback_after_each_question, include_in_class_manager, question_display_mode, shuffle_questions, shuffle_options, exam_mode, exam_require_fullscreen, exam_track_focus_exits, exam_allowed_focus_exits, exam_violation_action, created_by, published_at").eq("id", id).maybeSingle();
  if (error) {
    console.error(`[teacher-assignment] load failed: code=${error.code}; message=${error.message}`);
    throw new Error("Teacher assignment data could not be loaded.");
  }
  if (!assignment || assignment.created_by !== teacher.id) notFound();
  const isDraft = assignment.status === "draft";
  const [{ data: classes }, { data: linkedClasses }, { data: composition }, { data: variants }] = await Promise.all([
    supabase.from("classes").select("id, name, grade_level, academic_year").eq("teacher_id", teacher.id).order("grade_level"),
    supabase.from("assignment_classes").select("class_id").eq("assignment_id", id),
    supabase.from("assignment_questions").select("question_id, position, points").eq("assignment_id", id).order("position"),
    supabase.from("assignment_question_variants").select("slot_position, variant_index").eq("assignment_id", id).order("slot_position"),
  ]);
  const questionIds = composition?.map((item) => item.question_id) ?? [];
  const [{ data: rawQuestions }, { data: rawKeys }, { data: rawQuestionSkills }, { data: skillOptions }] = await Promise.all([
    questionIds.length ? supabase.from("questions").select("id, prompt, type, options, difficulty, icfes_competency").in("id", questionIds) : Promise.resolve({ data: [] as QuestionRow[] }),
    isDraft && questionIds.length ? supabase.from("question_keys").select("question_id, correct_answer, numeric_tolerance, explanation").in("question_id", questionIds) : Promise.resolve({ data: [] as QuestionKey[] }),
    isDraft && questionIds.length ? supabase.from("question_skills").select("question_id, weight, is_primary, skills(code, name)").in("question_id", questionIds) : Promise.resolve({ data: [] as QuestionSkill[] }),
    isDraft ? supabase.from("skills").select("code, name, domain").order("domain").order("code") : Promise.resolve({ data: [] as { code: string; name: string; domain: string }[] }),
  ]);
  const questions = (rawQuestions ?? []) as QuestionRow[]; const keys = (rawKeys ?? []) as QuestionKey[]; const questionSkills = (rawQuestionSkills ?? []) as QuestionSkill[];
  const variantCountBySlot = new Map<number, number>();
  for (const variant of (variants ?? []) as QuestionVariant[]) variantCountBySlot.set(variant.slot_position, Math.max(variantCountBySlot.get(variant.slot_position) ?? 1, variant.variant_index));
  const questionById = new Map(questions.map((question) => [question.id, question])); const keyByQuestion = new Map(keys.map((key) => [key.question_id, key])); const skillsByQuestion = new Map<string, DraftQuestion["skills"]>();
  for (const link of questionSkills) { const skill = Array.isArray(link.skills) ? link.skills[0] : link.skills; if (skill) skillsByQuestion.set(link.question_id, [...(skillsByQuestion.get(link.question_id) ?? []), { code: skill.code, name: skill.name, weight: Number(link.weight), is_primary: link.is_primary }]); }
  const draftQuestions: DraftQuestion[] = isDraft ? (composition ?? []).flatMap((item) => { const question = questionById.get(item.question_id); const key = keyByQuestion.get(item.question_id); return question && key ? [{ ...question, position: item.position, points: Number(item.points), options: question.options ?? null, correct_answer: key.correct_answer, numeric_tolerance: Number(key.numeric_tolerance), explanation: key.explanation, skills: skillsByQuestion.get(question.id) ?? [] }] : []; }) : [];
  const selectedClasses = new Set(linkedClasses?.map((item) => item.class_id)); const resultClasses = (classes ?? []).filter((classroom) => selectedClasses.has(classroom.id)); const selectedResultClass = messages.classId && selectedClasses.has(messages.classId) ? messages.classId : undefined; const isClosed = assignment.status === "closed"; const prioritizesResults = !isDraft;
  const resultVisibility = assignment.show_answers_after_submit ? "full_review" : assignment.show_score_after_submit ? "score_only" : "private";
  const settingsPanel = <section className="teacher-section assignment-settings-panel"><h2>Settings & classes</h2><form className="assessment-form" action={updateAssignment}><input name="assignment_id" type="hidden" value={assignment.id} /><div className="assessment-fields"><label>Title<input defaultValue={assignment.title} name="title" required /></label><DueDateInput dueAt={assignment.due_at} /></div><label className="wide-field">Description<textarea defaultValue={assignment.description ?? ""} name="description" rows={3} /></label><AssessmentPolicySettings initial={{ kind: assignment.kind, durationMinutes: assignment.duration_minutes, maxAttempts: assignment.max_attempts, questionDisplayMode: assignment.question_display_mode, showScoreAfterSubmit: assignment.show_score_after_submit, showAnswersAfterSubmit: assignment.show_answers_after_submit, showFeedbackAfterEachQuestion: assignment.show_feedback_after_each_question, shuffleQuestions: assignment.shuffle_questions, shuffleOptions: assignment.shuffle_options, examMode: assignment.exam_mode, examRequireFullscreen: assignment.exam_require_fullscreen, examTrackFocusExits: assignment.exam_track_focus_exits, examAllowedFocusExits: assignment.exam_allowed_focus_exits, examViolationAction: assignment.exam_violation_action }} /><label className="class-manager-grade-option"><input defaultChecked={assignment.include_in_class_manager} name="include_in_class_manager" type="checkbox" /><span><strong>Show this grade in the class manager</strong><small>Add submitted student scores to each linked class&apos;s achievement summary.</small></span></label><div className="class-checklist">{classes?.map((classroom) => <label key={classroom.id}><input defaultChecked={selectedClasses.has(classroom.id)} name="class_ids" type="checkbox" value={classroom.id} /> <span>{classroom.name} · Grade {classroom.grade_level} · {classroom.academic_year}</span></label>)}</div><button className="secondary-inline-button" type="submit">Save settings</button></form>{isDraft && <form action={publishAssignment}><input name="assignment_id" type="hidden" value={assignment.id} /><button className="teacher-button" type="submit">Publish assignment <span>→</span></button></form>}<LifecycleControls assignmentId={assignment.id} status={assignment.status} /><form action={duplicateAssignment}><input name="assignment_id" type="hidden" value={assignment.id} /><DuplicateButton /></form></section>;
  const hasVariants = variantCountBySlot.size > 0;
  const questionPanel = <section className="teacher-section draft-question-section" id="question-set"><div className="section-row"><div><h2>Question set</h2><p className="form-note">{isDraft ? "Edit, reorder, or remove draft questions here. These independent copies never alter historical assignments." : "Published questions are read-only to protect historical assessment records."}{hasVariants ? " Version labels show the alternatives randomized per student." : ""}</p></div>{isDraft && <Link className="secondary-inline-button" href={`/teacher/questions?assignment_id=${assignment.id}`}>Add from question bank</Link>}</div>{isDraft ? draftQuestions.length === (composition?.length ?? 0) ? <><DraftQuestionSet assignmentId={assignment.id} questions={draftQuestions} skills={skillOptions ?? []} />{hasVariants && <p className="form-note">Imported alternatives remain paired with each numbered slot. Editing above changes version 1; duplicate and re-import to replace all versions together.</p>}</> : <p className="notice notice-error">One or more draft questions are missing protected authoring data and cannot be edited.</p> : <div className="question-summary">{composition?.map((item) => { const question = questionById.get(item.question_id); const versionCount = variantCountBySlot.get(item.position) ?? 1; return question ? <article key={item.question_id}><span>#{item.position} · {question.type.replace("_", " ")} · {item.points} pts{versionCount > 1 ? ` · ${versionCount} versions` : ""}</span><strong><MathText>{question.prompt}</MathText></strong><small>Difficulty {question.difficulty}{question.icfes_competency ? ` · ${question.icfes_competency}` : ""}</small></article> : null; })}</div>}</section>;
  const resultsPanel = <div id="results-overview"><AssignmentResultsOverview assignmentId={assignment.id} classes={resultClasses} selectedClassId={selectedResultClass} examMode={assignment.exam_mode} allowedFocusExits={assignment.exam_allowed_focus_exits} questionSet={prioritizesResults ? questionPanel : undefined} tabbed={prioritizesResults} /></div>;
  return <main className={`teacher-main assessment-page${prioritizesResults ? " results-first-assignment-page" : ""}`}><Link className="back-link" href="/teacher/assignments">← Assignments</Link><section className="page-heading"><div><p className="eyebrow">{assignment.status === "published" ? "Live assessment" : isClosed ? "Closed assessment" : "Private draft"}</p><h1>{assignment.title}</h1><p>{assignment.description || "No description provided."}</p><AssignmentDue dueAt={assignment.due_at} status={assignment.status} /></div><span className={`status-pill status-${assignment.status}`}>{assignment.status}</span></section>{messages.error && <p className="notice notice-error" role="alert">{messages.error}</p>}{messages.success && <p className="notice notice-success">{messages.success}</p>}
    {prioritizesResults ? <><section aria-label="Assignment actions" className="assignment-results-commandbar"><div className="assignment-results-commandbar-copy"><strong>Results workspace</strong><span>Review performance first, then switch between focused views.</span></div><details><summary><span>Edit assignment</span><b aria-hidden="true">+</b></summary>{settingsPanel}</details></section><ResultReleaseControls assignmentId={assignment.id} kind={assignment.kind} visibility={resultVisibility} />{resultsPanel}</> : <>{settingsPanel}{questionPanel}{resultsPanel}</>}<Link className="back-link" href="/teacher/assignments">Back to assignments</Link></main>;
}
