import Link from "next/link";
import { notFound } from "next/navigation";
import { duplicateAssignment, publishAssignment, updateAssignment } from "../../assignment-actions";
import DraftQuestionSet, { type DraftQuestion } from "../draft-question-set";
import DuplicateButton from "../duplicate-button";
import MathText from "@/app/components/math-text";
import { requireTeacher } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type AssignmentPageProps = { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> };
type QuestionRow = { id: string; prompt: string; type: DraftQuestion["type"]; options: DraftQuestion["options"]; difficulty: number; icfes_competency: string | null };
type QuestionKey = { question_id: string; correct_answer: string; numeric_tolerance: number; explanation: string | null };
type QuestionSkill = { question_id: string; weight: number; is_primary: boolean; skills: { code: string; name: string } | { code: string; name: string }[] | null };

export default async function AssignmentDetailPage({ params, searchParams }: AssignmentPageProps) {
  const teacher = await requireTeacher(); const { id } = await params; const messages = await searchParams; const supabase = await createClient();
  const { data: assignment, error } = await supabase.from("assignments").select("id, title, description, kind, status, due_at, duration_minutes, max_attempts, show_score_after_submit, show_answers_after_submit, shuffle_questions, created_by, published_at").eq("id", id).maybeSingle();
  if (error || !assignment || assignment.created_by !== teacher.id) notFound();
  const isDraft = assignment.status === "draft";
  const [{ data: classes }, { data: linkedClasses }, { data: composition }, { data: attempts }] = await Promise.all([
    supabase.from("classes").select("id, name, grade_level, academic_year").eq("teacher_id", teacher.id).order("grade_level"),
    supabase.from("assignment_classes").select("class_id").eq("assignment_id", id),
    supabase.from("assignment_questions").select("question_id, position, points").eq("assignment_id", id).order("position"),
    supabase.from("attempts").select("id, student_id, attempt_number, status, score, max_score, submitted_at, profiles(full_name, email)").eq("assignment_id", id).order("submitted_at", { ascending: false }),
  ]);
  const questionIds = composition?.map((item) => item.question_id) ?? [];
  const [{ data: rawQuestions }, { data: rawKeys }, { data: rawQuestionSkills }, { data: skillOptions }] = await Promise.all([
    questionIds.length ? supabase.from("questions").select("id, prompt, type, options, difficulty, icfes_competency").in("id", questionIds) : Promise.resolve({ data: [] as QuestionRow[] }),
    isDraft && questionIds.length ? supabase.from("question_keys").select("question_id, correct_answer, numeric_tolerance, explanation").in("question_id", questionIds) : Promise.resolve({ data: [] as QuestionKey[] }),
    isDraft && questionIds.length ? supabase.from("question_skills").select("question_id, weight, is_primary, skills(code, name)").in("question_id", questionIds) : Promise.resolve({ data: [] as QuestionSkill[] }),
    isDraft ? supabase.from("skills").select("code, name, domain").order("domain").order("code") : Promise.resolve({ data: [] as { code: string; name: string; domain: string }[] }),
  ]);
  const questions = (rawQuestions ?? []) as QuestionRow[]; const keys = (rawKeys ?? []) as QuestionKey[]; const questionSkills = (rawQuestionSkills ?? []) as QuestionSkill[];
  const questionById = new Map(questions.map((question) => [question.id, question])); const keyByQuestion = new Map(keys.map((key) => [key.question_id, key])); const skillsByQuestion = new Map<string, DraftQuestion["skills"]>();
  for (const link of questionSkills) { const skill = Array.isArray(link.skills) ? link.skills[0] : link.skills; if (skill) skillsByQuestion.set(link.question_id, [...(skillsByQuestion.get(link.question_id) ?? []), { code: skill.code, name: skill.name, weight: Number(link.weight), is_primary: link.is_primary }]); }
  const draftQuestions: DraftQuestion[] = isDraft ? (composition ?? []).flatMap((item) => { const question = questionById.get(item.question_id); const key = keyByQuestion.get(item.question_id); return question && key ? [{ ...question, position: item.position, points: Number(item.points), options: question.options ?? null, correct_answer: key.correct_answer, numeric_tolerance: Number(key.numeric_tolerance), explanation: key.explanation, skills: skillsByQuestion.get(question.id) ?? [] }] : []; }) : [];
  const selectedClasses = new Set(linkedClasses?.map((item) => item.class_id));
  return <main className="teacher-main assessment-page"><Link className="back-link" href="/teacher/assignments">← Assignments</Link><section className="page-heading"><div><p className="eyebrow">{assignment.status === "published" ? "Live assessment" : "Private draft"}</p><h1>{assignment.title}</h1><p>{assignment.description || "No description provided."}</p></div><span className={`status-pill status-${assignment.status}`}>{assignment.status}</span></section>{messages.error && <p className="notice notice-error" role="alert">{messages.error}</p>}{messages.success && <p className="notice notice-success">{messages.success}</p>}
    <section className="teacher-section"><h2>Settings & classes</h2><form className="assessment-form" action={updateAssignment}><input name="assignment_id" type="hidden" value={assignment.id} /><div className="assessment-fields"><label>Title<input defaultValue={assignment.title} name="title" required /></label><label>Type<select defaultValue={assignment.kind} name="kind"><option value="homework">Homework</option><option value="quiz">Quiz</option><option value="test">Test</option></select></label><label>Due date and time<input defaultValue={assignment.due_at ? new Date(assignment.due_at).toISOString().slice(0, 16) : ""} name="due_at" type="datetime-local" /></label><label>Duration in minutes<input defaultValue={assignment.duration_minutes ?? ""} min="1" name="duration_minutes" type="number" /></label><label>Maximum attempts<input defaultValue={assignment.max_attempts} min="1" name="max_attempts" required type="number" /></label></div><label className="wide-field">Description<textarea defaultValue={assignment.description ?? ""} name="description" rows={3} /></label><div className="assignment-toggles"><label><input defaultChecked={assignment.show_score_after_submit} name="show_score_after_submit" type="checkbox" /> Show score after submit</label><label><input defaultChecked={assignment.show_answers_after_submit} name="show_answers_after_submit" type="checkbox" /> Show answer review after submit</label><label><input defaultChecked={assignment.shuffle_questions} name="shuffle_questions" type="checkbox" /> Shuffle question order</label></div><div className="class-checklist">{classes?.map((classroom) => <label key={classroom.id}><input defaultChecked={selectedClasses.has(classroom.id)} name="class_ids" type="checkbox" value={classroom.id} /> <span>{classroom.name} · Grade {classroom.grade_level} · {classroom.academic_year}</span></label>)}</div><button className="secondary-inline-button" type="submit">Save settings</button></form>{isDraft && <form action={publishAssignment}><input name="assignment_id" type="hidden" value={assignment.id} /><button className="teacher-button" type="submit">Publish assignment <span>→</span></button></form>}<form action={duplicateAssignment}><input name="assignment_id" type="hidden" value={assignment.id} /><DuplicateButton /></form></section>
    <section className="teacher-section draft-question-section"><div className="section-row"><div><h2>Question set</h2><p className="form-note">{isDraft ? "Edit, reorder, or remove draft questions here. These independent copies never alter historical assignments." : "Published questions are read-only to protect historical assessment records."}</p></div>{isDraft && <Link className="secondary-inline-button" href={`/teacher/questions?assignment_id=${assignment.id}`}>Add from question bank</Link>}</div>{isDraft ? draftQuestions.length === (composition?.length ?? 0) ? <DraftQuestionSet assignmentId={assignment.id} questions={draftQuestions} skills={skillOptions ?? []} /> : <p className="notice notice-error">One or more draft questions are missing protected authoring data and cannot be edited.</p> : <div className="question-summary">{composition?.map((item) => { const question = questionById.get(item.question_id); return question ? <article key={item.question_id}><span>#{item.position} · {question.type.replace("_", " ")} · {item.points} pts</span><strong><MathText>{question.prompt}</MathText></strong><small>Difficulty {question.difficulty}{question.icfes_competency ? ` · ${question.icfes_competency}` : ""}</small></article> : null; })}</div>}</section>
    <section className="teacher-section results-section"><div className="section-row"><div><p className="eyebrow">Results</p><h2>Attempts</h2></div><span className="muted-count">{attempts?.length ?? 0} started</span></div>{attempts?.length ? <div className="attempt-list">{attempts.map((attempt) => { const profile = Array.isArray(attempt.profiles) ? attempt.profiles[0] : attempt.profiles; const contents = <><strong>{profile?.full_name || profile?.email || "Student"}</strong><span>Attempt {attempt.attempt_number} · {attempt.status}</span><b>{attempt.status === "submitted" ? `${attempt.score ?? 0}/${attempt.max_score ?? 0} · View →` : "In progress"}</b></>; return attempt.status === "submitted" ? <Link href={`/teacher/assignments/${id}/attempts/${attempt.id}`} key={attempt.id}>{contents}</Link> : <div key={attempt.id}>{contents}</div>; })}</div> : <p className="form-note">No student has started this assignment yet.</p>}</section><Link className="back-link" href="/teacher/assignments">Back to assignments</Link></main>;
}
