import { updateStudentProfile } from "../actions";
import { requireTeacher } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type PageProps = { searchParams: Promise<{ error?: string; success?: string }> };
type Student = { id: string; full_name: string | null; email: string | null; grade_level: 11 | 12 | null };
export default async function StudentsPage({ searchParams }: PageProps) {
  await requireTeacher(); const messages = await searchParams; const supabase = await createClient(); const [{ data: students }, { data: memberships }, { data: classes }] = await Promise.all([supabase.from("profiles").select("id, full_name, email, grade_level").eq("role", "student").order("full_name"), supabase.from("class_members").select("student_id, class_id"), supabase.from("classes").select("id, name")]);
  const classNames = new Map(classes?.map((classroom) => [classroom.id, classroom.name]) ?? []); const studentClasses = new Map<string, string[]>(); memberships?.forEach(({ student_id, class_id }) => studentClasses.set(student_id, [...(studentClasses.get(student_id) ?? []), classNames.get(class_id) ?? "Class"]));
  return <main className="teacher-main"><section className="page-heading"><p className="eyebrow">Student accounts</p><h1>Students</h1><p>Manage academic profile details for existing accounts.</p></section>{messages.error && <p className="notice notice-error" role="alert">{messages.error}</p>}{messages.success && <p className="notice notice-success">{messages.success}</p>}<section className="teacher-section">{students?.length ? <div className="student-table"><div className="student-table-head"><span>Student</span><span>Email</span><span>Classes</span><span>Academic details</span></div>{(students as Student[]).map((student) => <div className="student-row" key={student.id}><strong>{student.full_name || "Unnamed student"}</strong><span>{student.email}</span><span>{studentClasses.get(student.id)?.join(", ") || "Not assigned"}</span><form action={updateStudentProfile}><input name="student_id" type="hidden" value={student.id} /><input aria-label={`Name for ${student.email}`} defaultValue={student.full_name ?? ""} name="full_name" placeholder="Full name" /><select aria-label={`Grade for ${student.email}`} defaultValue={student.grade_level ?? ""} name="grade_level"><option value="">No grade</option><option value="11">Grade 11</option><option value="12">Grade 12</option></select><button className="text-button" type="submit">Save</button></form></div>)}</div> : <div className="empty-state"><span aria-hidden="true">∑</span><h3>No student accounts found.</h3><p>Create students in Supabase Auth first. Their profiles will appear here automatically.</p></div>}</section></main>;
}
