import Link from "next/link";

const focusAreas = [
  ["01", "Practice with purpose", "Build confidence through focused, skill-by-skill practice."],
  ["02", "Stay on top of work", "Keep homework, quizzes, and tests in one clear place."],
  ["03", "See your progress", "Understand what you know and what to work on next."],
];

export default function Home() {
  return <main className="landing-shell"><section className="hero-grid"><div className="orb orb-one" /><div className="orb orb-two" /><nav className="site-nav" aria-label="Main navigation"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true">∑</span><span>Jaguar Math</span></Link><Link className="nav-login" href="/login">Student Login <span aria-hidden="true">→</span></Link></nav><div className="hero-copy"><p className="eyebrow">G11 &amp; G12 mathematics</p><h1>Make every <em>step</em> count.</h1><p className="hero-description">Your space for mathematical practice, assignments, assessments, and the progress that follows.</p><Link className="primary-button" href="/login">Student Login <span aria-hidden="true">→</span></Link></div><div className="math-panel" aria-label="Mathematics illustration"><div className="panel-topline"><span>SKILL PATH</span><span>11 · 12</span></div><div className="formula">f&apos;(x) = <span>lim</span><sub>h→0</sub> <strong>f(x+h) − f(x)</strong><small>h</small></div><div className="curve" aria-hidden="true"><svg viewBox="0 0 420 190" preserveAspectRatio="none"><path d="M-10 158 C88 155, 110 27, 203 88 S299 177, 440 18" /><path className="curve-faint" d="M0 155 H420 M112 0 V190" /></svg></div><div className="point point-one" /><div className="point point-two" /><div className="point point-three" /><div className="panel-footer"><span>calculus</span><span>in progress</span></div></div></section><section className="focus-section" aria-labelledby="focus-title"><div className="section-heading"><p className="eyebrow">A clear way forward</p><h2 id="focus-title">Math class, organized around your learning.</h2></div><div className="focus-list">{focusAreas.map(([number, title, description]) => <article className="focus-card" key={number}><span className="card-number">{number}</span><h3>{title}</h3><p>{description}</p><span className="card-arrow" aria-hidden="true">↗</span></article>)}</div></section></main>;
}
