"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import MathText from "@/app/components/math-text";
import { saveStudentResponse, submitStudentAttempt } from "../actions";

type Question = { id: string; prompt: string; type: string; options: { id: string; text: string }[] | null; points: number; answer: string };
export default function AssessmentRunner({ attemptId, startedAt, durationMinutes, questions, responsesClosed = false }: { attemptId: string; startedAt: string; durationMinutes: number | null; questions: Question[]; responsesClosed?: boolean }) {
  const router = useRouter(); const [answers, setAnswers] = useState(() => Object.fromEntries(questions.map((question) => [question.id, question.answer ?? ""]))); const [notice, setNotice] = useState(""); const [pending, startTransition] = useTransition(); const [savingQuestionId, setSavingQuestionId] = useState<string | null>(null);
  const expiresAt = useMemo(() => durationMinutes ? new Date(startedAt).getTime() + durationMinutes * 60_000 : null, [durationMinutes, startedAt]); const [remaining, setRemaining] = useState(() => expiresAt ? Math.max(0, expiresAt - Date.now()) : 0);
  useEffect(() => { if (!expiresAt) return; const timer = window.setInterval(() => setRemaining(Math.max(0, expiresAt - Date.now())), 1000); return () => window.clearInterval(timer); }, [expiresAt]);
  const save = (questionId: string, answer: string) => { if (pending || responsesClosed) return; setAnswers((current) => ({ ...current, [questionId]: answer })); setSavingQuestionId(questionId); startTransition(async () => { const result = await saveStudentResponse(attemptId, questionId, answer); if (result.error) setNotice(result.error); else setNotice("Saved."); setSavingQuestionId(null); }); };
  const submit = () => { if (pending) return; startTransition(async () => { const result = await submitStudentAttempt(attemptId); if (result.error) setNotice(result.error); else router.refresh(); }); };
  const clock = `${String(Math.floor(remaining / 60_000)).padStart(2, "0")}:${String(Math.floor((remaining % 60_000) / 1000)).padStart(2, "0")}`;
  return <section className="runner"><div className="runner-header"><div><p className="eyebrow">Active attempt</p><h2>{questions.length} questions</h2></div>{expiresAt && <strong className={remaining === 0 ? "timer-expired" : ""}>Time remaining: {clock}</strong>}</div>{responsesClosed && <p className="form-note lifecycle-note">Overdue. Answers can no longer be changed, but you may submit the work already saved.</p>}{questions.map((question, index) => <article className="student-question" key={question.id}><div className="question-number">{index + 1} · {question.points} {question.points === 1 ? "point" : "points"}</div><div className="question-prompt"><MathText>{question.prompt}</MathText></div>{question.type === "multiple_choice" ? <div className="answer-options">{question.options?.map((option) => <label key={option.id}><input checked={answers[question.id] === option.id} disabled={pending || responsesClosed || (remaining === 0 && Boolean(expiresAt))} name={question.id} onChange={() => save(question.id, option.id)} type="radio" /> <b>{option.id}</b> <MathText>{option.text}</MathText></label>)}</div> : <label className="answer-text">Your answer<input disabled={pending || responsesClosed || (remaining === 0 && Boolean(expiresAt))} onBlur={(event) => save(question.id, event.target.value)} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.value }))} value={answers[question.id]} /></label>}</article>)}{notice && <p className="notice notice-error" role="status">{notice}</p>}<button aria-live="polite" className="teacher-button" disabled={pending} onClick={submit} type="button">{savingQuestionId ? "Saving..." : pending ? "Submitting..." : "Submit attempt"} <span aria-hidden="true">→</span></button></section>;
}
