"use client";

import { useState } from "react";
import styles from "./exam-mode-settings.module.css";

export default function ExamModeSettings({ initial = {}, forcedEnabled = false }: { initial?: { enabled?: boolean; requireFullscreen?: boolean; trackFocusExits?: boolean; allowedFocusExits?: number; violationAction?: "warn" | "auto_submit" }; forcedEnabled?: boolean }) {
  const [enabled, setEnabled] = useState(initial.enabled ?? false);
  const active = forcedEnabled || enabled;
  return <section aria-labelledby="exam-mode-heading" className={styles.settings}><div className={styles.heading}><div><h3 id="exam-mode-heading">Exam Mode</h3>{forcedEnabled && <small>Required for tests</small>}</div><label className={styles.toggle}><input checked={active} disabled={forcedEnabled} name={forcedEnabled ? undefined : "exam_mode"} onChange={(event) => setEnabled(event.target.checked)} type="checkbox" /> Enable{forcedEnabled && <input name="exam_mode" type="hidden" value="on" />}</label></div>{active && <div className={styles.fields}><p>Exam Mode records page/fullscreen interruptions. A normal webpage cannot fully lock a student&apos;s device.</p><label><input defaultChecked={initial.requireFullscreen ?? true} disabled={forcedEnabled} name={forcedEnabled ? undefined : "exam_require_fullscreen"} type="checkbox" /> Require fullscreen{forcedEnabled && <input name="exam_require_fullscreen" type="hidden" value="on" />}</label><label><input defaultChecked={initial.trackFocusExits ?? true} disabled={forcedEnabled} name={forcedEnabled ? undefined : "exam_track_focus_exits"} type="checkbox" /> Track focus exits{forcedEnabled && <input name="exam_track_focus_exits" type="hidden" value="on" />}</label><label className={styles.field}>Allowed focus exits<input defaultValue={initial.allowedFocusExits ?? 2} min="0" name="exam_allowed_focus_exits" required type="number" /></label><label className={styles.field}>When the limit is exceeded<select defaultValue={initial.violationAction ?? "warn"} name="exam_violation_action"><option value="warn">Flag for teacher review (recommended)</option><option value="auto_submit">Automatically submit</option></select></label><p className="form-note">Focus exits are activity signals, not proof of cheating. Review-only mode protects students from accidental interruptions.</p></div>}</section>;
}
