import Link from "next/link";
import { notFound } from "next/navigation";
import { requireTeacher } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { progressByDomain, progressPercent, progressStatus, type SkillProgress } from "@/lib/skill-progress";

type ClassProgress = SkillProgress & { student_id: string; student_name: string | null; student_email: string | null };
type PageProps = { params: Promise<{ id: string }> };
export default async function ClassProgressPage({ params }: PageProps) {
  const teacher = await requireTeacher(); const { id } = await params; const supabase = await createClient(); const { data: classroom } = await supabase.from("classes").select("id, name, teacher_id").eq("id", id).maybeSingle(); if (!classroom || classroom.teacher_id !== teacher.id) notFound(); const { data } = await supabase.rpc("get_class_skill_progress", { p_class_id: id }); const rows = (data ?? []) as ClassProgress[];
  return <main className="teacher-main assessment-page"><Link className="back-link" href={`/teacher/classes/${id}`}>← {classroom.name}</Link><section className="page-heading"><p className="eyebrow">Class progress</p><h1>{classroom.name}</h1><p>Submitted evidence from assessments you assigned to this class.</p></section>{rows.length ? <section className="progress-domains teacher-progress">{progressByDomain(rows).map(([domain, domainRows], index) => { const skills = [...new Map(domainRows.map((row) => [row.skill_code, row])).values()]; const students = [...new Map(domainRows.map((row) => [row.student_id, { id: row.student_id, name: row.student_name || row.student_email || "Student" }])).values()]; return <details key={domain} open={index === 0}><summary>{domain}<span>{skills.length} skills</span></summary><div className="class-skill-summary">{skills.map((skill) => { const related = domainRows.filter((row) => row.skill_code === skill.skill_code); const accuracy = Math.round(related.reduce((total, row) => total + Number(row.accuracy), 0) / related.length); const statuses = related.map(progressStatus); return <article key={skill.skill_code}><strong>{skill.skill_name}</strong><span>{related.length} students · {accuracy}% average · {statuses.filter((status) => status === "Strong").length} Strong · {statuses.filter((status) => status === "Developing").length} Developing · {statuses.filter((status) => status === "Needs work").length} Needs work</span></article>; })}</div><div className="class-progress-table"><table><thead><tr><th>Student</th>{skills.map((skill) => <th key={skill.skill_code}>{skill.skill_name}</th>)}</tr></thead><tbody>{students.map((student) => <tr key={student.id}><th><Link href={`/teacher/students/${student.id}`}>{student.name}</Link></th>{skills.map((skill) => { const row = domainRows.find((item) => item.student_id === student.id && item.skill_code === skill.skill_code); return <td key={skill.skill_code}>{row ? <span className={`progress-status ${progressStatus(row).toLowerCase().replaceAll(" ", "-")}`}>{progressPercent(row)}%</span> : "—"}</td>; })}</tr>)}</tbody></table></div></details>; })}</section> : <section className="teacher-section"><h2>No submitted assessment evidence yet.</h2><p className="form-note">Class progress will appear after students submit assessments assigned to this class.</p></section>}</main>;
}
