import Link from "next/link";
import { notFound } from "next/navigation";
import AssessmentRunner from "../assessment-runner";
import StartAssignmentButton from "../start-assignment-button";
import AssignmentDue from "@/app/components/assignment-due";
import MathText from "@/app/components/math-text";
import { requireStudent } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type AssignmentPageProps = { params: Promise<{ id: string }> };
export default async function StudentAssignmentPage({ params }: AssignmentPageProps) {
  const student = await requireStudent(); const { id } = await params; const supabase = await createClient(); const { data: assignment, error } = await supabase.from("assignments").select("id, title, description, kind, status, due_at, duration_minutes, max_attempts, show_score_after_submit, show_answers_after_submit, shuffle_questions").eq("id", id).in("status", ["published", "closed"]).maybeSingle();
  if (error || !assignment) notFound();
  const { data: attempts } = await supabase.from("attempts").select("id, status, started_at, submitted_at, score, max_score, attempt_number").eq("assignment_id", id).eq("student_id", student.id).order("attempt_number", { ascending: false }); const activeAttempt = attempts?.find((attempt) => attempt.status === "in_progress"); const latestSubmitted = attempts?.find((attempt) => attempt.status === "submitted");
  const { data: composition } = await supabase.from("assignment_questions").select("question_id, position, points").eq("assignment_id", id).order("position"); const ids = composition?.map((item) => item.question_id) ?? []; const { data: questions } = ids.length ? await supabase.from("questions").select("id, prompt, type, options").in("id", ids) : { data: [] as { id: string; prompt: string; type: string; options: { id: string; text: string }[] | null }[] }; const questionById = new Map((questions ?? []).map((question) => [question.id, question]));
  let responses: { question_id: string; student_answer: string | null }[] = []; if (activeAttempt) { const { data } = await supabase.from("responses").select("question_id, student_answer").eq("attempt_id", activeAttempt.id); responses = data ?? []; }
  let submittedResponses: { question_id: string; student_answer: string | null; is_correct: boolean | null; points_awarded: number | null }[] = []; if (latestSubmitted) { const { data } = await supabase.from("responses").select("question_id, student_answer, is_correct, points_awarded").eq("attempt_id", latestSubmitted.id); submittedResponses = data ?? []; }
  const answerByQuestion = new Map(responses.map((response) => [response.question_id, response.student_answer ?? ""])); const runnerQuestions = (composition ?? []).map((item) => { const question = questionById.get(item.question_id); return question && { ...question, points: Number(item.points), answer: answerByQuestion.get(item.question_id) ?? "" }; }).filter(Boolean) as { id: string; prompt: string; type: string; options: { id: string; text: string }[] | null; points: number; answer: string }[];
  if (assignment.shuffle_questions && activeAttempt) runnerQuestions.sort((left, right) => `${activeAttempt.id}${left.id}`.localeCompare(`${activeAttempt.id}${right.id}`));
  let review: { question_id: string; prompt: string; question_type: string; options: { id: string; text: string }[] | null; student_answer: string | null; is_correct: boolean | null; points_awarded: number | null; points: number; correct_answer: string; explanation: string | null }[] = [];
  if (latestSubmitted && assignment.show_answers_after_submit) { const { data } = await supabase.rpc("get_attempt_answer_review", { p_attempt_id: latestSubmitted.id }); review = data ?? []; }
  const submittedResponseByQuestion = new Map(submittedResponses.map((response) => [response.question_id, response])); const reviewByQuestion = new Map(review.map((question) => [question.question_id, question]));
  const isClosed = assignment.status === "closed"; const isOverdue = Boolean(assignment.due_at && new Date(assignment.due_at) < new Date()); const attemptsUsed = attempts?.length ?? 0; const canRetry = !isClosed && !activeAttempt && attemptsUsed < assignment.max_attempts && !isOverdue;
  return <main className="student-page"><div className="student-container"><Link className="back-link" href="/student">← Your assignments</Link><section className="student-intro"><p className="eyebrow">{isClosed ? "Closed" : assignment.kind}</p><h1>{assignment.title}</h1><p>{assignment.description || "Complete each question, then submit your attempt."}</p><AssignmentDue dueAt={assignment.due_at} status={assignment.status} /></section>{activeAttempt && !isClosed ? <AssessmentRunner attemptId={activeAttempt.id} durationMinutes={assignment.duration_minutes} questions={runnerQuestions} responsesClosed={isOverdue} startedAt={activeAttempt.started_at} /> : latestSubmitted ? <section className="student-results"><p className="eyebrow">Submitted</p><h2>Attempt {latestSubmitted.attempt_number}</h2>{isClosed && activeAttempt && <p className="form-note lifecycle-note">This assignment is closed. Your in-progress attempt is preserved, but it cannot be changed or submitted.</p>}{assignment.show_score_after_submit && <p className="result-score">{latestSubmitted.score ?? 0} / {latestSubmitted.max_score ?? 0}</p>}{!assignment.show_score_after_submit && <p>Your teacher will share the score when it is ready.</p>}<div className="answer-review"><h3>Question breakdown</h3>{(composition ?? []).map((item) => { const question = questionById.get(item.question_id); const response = submittedResponseByQuestion.get(item.question_id); const answerReview = reviewByQuestion.get(item.question_id); return question ? <article key={item.question_id}><span>Question {item.position} · {response?.is_correct ? "Correct" : "Incorrect"} · {response?.points_awarded ?? 0}/{item.points}</span><strong><MathText>{question.prompt}</MathText></strong><p>Your answer: {response?.student_answer || "No response"}</p>{answerReview && <><p>Correct answer: <MathText>{answerReview.correct_answer}</MathText></p>{answerReview.explanation && <p>Explanation: <MathText>{answerReview.explanation}</MathText></p>}</>}</article> : null; })}</div>{canRetry && <StartAssignmentButton assignmentId={assignment.id} label="Start another attempt" />}</section> : canRetry ? <section className="student-results"><p className="form-note">You have {assignment.max_attempts} attempt{assignment.max_attempts === 1 ? "" : "s"} available.</p><StartAssignmentButton assignmentId={assignment.id} /></section> : <section className="student-results"><h2>{isClosed ? "This assignment is closed." : "This assignment is no longer available."}</h2><p>{isClosed ? activeAttempt ? "Your in-progress attempt is preserved, but it cannot be changed or submitted." : "Your teacher has closed this assignment." : "The due date has passed or all attempts have been used."}</p></section>}</div></main>;
}
